"""Curated, hand-checked vocabularies for the ABO converter.

Everything here answers one question: *can a person see this in a catalogue photo?*
ABO's metadata is seller-supplied and mixes visual facts ("leather", "round") with
facts that are invisible in a photo ("100% polyester microfiber", model names, pack
counts). Only the visible half is kept, and every kept value gets a human-readable
label plus a coarse group so sibling distractors can be drawn from the group.
"""

# --- product types ------------------------------------------------------------
# product_type -> (readable label, coarse group used for hard distractors)
# Department-style buckets (HOME, GROCERY, ACCESSORY, BISS, ABIS_*, KITCHEN,
# OFFICE_PRODUCTS, SPORTING_GOODS, HEALTH_PERSONAL_CARE, BEAUTY, PET_SUPPLIES,
# TOOLS, FURNITURE, OUTDOOR_LIVING, PANTRY ...) are deliberately absent: they name a
# shelf, not a thing you can identify in a photo. Food/consumable types are absent
# too, because their photos show packaging rather than the product.
PRODUCT_TYPES = {
    # footwear
    "SHOES": ("shoe", "footwear"),
    "BOOT": ("boot", "footwear"),
    "SANDAL": ("sandal", "footwear"),
    "TECHNICAL_SPORT_SHOE": ("athletic shoe", "footwear"),
    "SHOE_INSERT": ("shoe insole", "footwear"),
    # seating
    "CHAIR": ("chair", "seating"),
    "SOFA": ("sofa", "seating"),
    "OTTOMAN": ("ottoman", "seating"),
    "STOOL_SEATING": ("stool", "seating"),
    "BENCH": ("bench", "seating"),
    "BEAN_BAG_CHAIR": ("bean bag chair", "seating"),
    # tables and desks
    "TABLE": ("table", "table_desk"),
    "DESK": ("desk", "table_desk"),
    "AV_FURNITURE": ("media console", "table_desk"),
    # storage furniture
    "CABINET": ("cabinet", "storage_furniture"),
    "SHELF": ("shelf unit", "storage_furniture"),
    "DRESSER": ("dresser", "storage_furniture"),
    "STORAGE_RACK": ("storage rack", "storage_furniture"),
    "STORAGE_DRAWER": ("storage drawer", "storage_furniture"),
    "CLOTHES_RACK": ("clothes rack", "storage_furniture"),
    "BOTTLE_RACK": ("bottle rack", "storage_furniture"),
    "ROOM_DIVIDER": ("room divider", "storage_furniture"),
    # beds
    "BED": ("bed", "bed"),
    "BED_FRAME": ("bed frame", "bed"),
    "HEADBOARD": ("headboard", "bed"),
    "MATTRESS": ("mattress", "bed"),
    "AIR_MATTRESS": ("air mattress", "bed"),
    # soft furnishing
    "FLAT_SHEET": ("bed sheet", "bedding"),
    "PILLOW": ("pillow", "bedding"),
    "BLANKET": ("blanket", "bedding"),
    "FURNITURE_COVER": ("furniture cover", "bedding"),
    "TOWEL_HOLDER": ("towel holder", "bath_hardware"),
    # lighting
    "LAMP": ("lamp", "lighting"),
    "LIGHT_FIXTURE": ("light fixture", "lighting"),
    "LIGHT_BULB": ("light bulb", "lighting"),
    "STRING_LIGHT": ("string lights", "lighting"),
    "CANDLE": ("candle", "lighting"),
    "CANDLE_HOLDER": ("candle holder", "lighting"),
    "HOME_LIGHTING_ACCESSORY": ("lamp shade", "lighting"),
    # jewellery and watches
    "FINERING": ("ring", "jewelry"),
    "RING": ("ring", "jewelry"),
    "FASHIONRING": ("ring", "jewelry"),
    "FINEEARRING": ("earrings", "jewelry"),
    "EARRING": ("earrings", "jewelry"),
    "FASHIONEARRING": ("earrings", "jewelry"),
    "NECKLACE": ("necklace", "jewelry"),
    "BRACELET": ("bracelet", "jewelry"),
    "CHARM": ("charm", "jewelry"),
    "JEWELRY_SET": ("jewellery set", "jewelry"),
    "WATCH": ("watch", "jewelry"),
    "JEWELRY_STORAGE": ("jewellery box", "jewelry"),
    # bags and luggage
    "HANDBAG": ("handbag", "bags"),
    "BACKPACK": ("backpack", "bags"),
    "TOTE_BAG": ("tote bag", "bags"),
    "SUITCASE": ("suitcase", "bags"),
    "LUGGAGE": ("luggage", "bags"),
    "WALLET": ("wallet", "bags"),
    "COSMETIC_CASE": ("cosmetic case", "bags"),
    "CARRYING_CASE_OR_BAG": ("carrying case", "bags"),
    "GOLF_CLUB_BAG": ("golf bag", "bags"),
    "CAMERA_BAGS_AND_CASES": ("camera bag", "bags"),
    # phone and tablet accessories
    "CELLULAR_PHONE_CASE": ("phone case", "phone_accessory"),
    "PORTABLE_ELECTRONIC_DEVICE_COVER": ("tablet case", "phone_accessory"),
    "SCREEN_PROTECTOR": ("screen protector", "phone_accessory"),
    "PORTABLE_ELECTRONIC_DEVICE_STAND": ("phone stand", "phone_accessory"),
    "PORTABLE_ELECTRONIC_DEVICE_MOUNT": ("phone mount", "phone_accessory"),
    "POWER_BANK": ("power bank", "phone_accessory"),
    # computing
    "KEYBOARDS": ("computer keyboard", "computer_peripheral"),
    "INPUT_MOUSE": ("computer mouse", "computer_peripheral"),
    "MOUSE_PAD": ("mouse pad", "computer_peripheral"),
    "MULTIPORT_HUB": ("usb hub", "computer_peripheral"),
    "FLASH_DRIVE": ("usb flash drive", "computer_peripheral"),
    "INPUT_PEN": ("stylus pen", "computer_peripheral"),
    "NOTEBOOK_COMPUTER": ("laptop computer", "computer_peripheral"),
    "MONITOR": ("computer monitor", "computer_peripheral"),
    "PRINTER": ("printer", "computer_peripheral"),
    "SCANNER": ("scanner", "computer_peripheral"),
    "CALCULATOR": ("calculator", "computer_peripheral"),
    # audio
    "HEADPHONES": ("headphones", "audio"),
    "SPEAKERS": ("loudspeaker", "audio"),
    "COMPUTER_SPEAKER": ("computer speaker", "audio"),
    "MICROPHONE": ("microphone", "audio"),
    "RADIO": ("radio", "audio"),
    "THERMOS": ("vacuum flask", "tableware"),
    # cookware
    "SAUTE_FRY_PAN": ("frying pan", "cookware"),
    "DUTCH_OVENS": ("dutch oven", "cookware"),
    "BAKING_PAN": ("baking pan", "cookware"),
    "SHEET_PAN": ("sheet pan", "cookware"),
    "ROASTING_PAN": ("roasting pan", "cookware"),
    "CASSEROLES": ("casserole dish", "cookware"),
    "PRESSURE_COOKER": ("pressure cooker", "cookware"),
    "KITCHEN_KNIFE": ("kitchen knife", "cookware"),
    "CUTTING_BOARD": ("cutting board", "cookware"),
    "MEASURING_CUP": ("measuring cup", "cookware"),
    "CAN_OPENER": ("can opener", "cookware"),
    "POT_HOLDER": ("pot holder", "cookware"),
    # tableware
    "DISHWARE_PLATE": ("plate", "tableware"),
    "DISHWARE_BOWL": ("bowl", "tableware"),
    "DISHWARE_PLACE_SETTING": ("dinnerware set", "tableware"),
    "FLATWARE": ("cutlery", "tableware"),
    "DRINKING_CUP": ("drinking cup", "tableware"),
    "PITCHER": ("pitcher", "tableware"),
    "BOTTLE": ("bottle", "tableware"),
    "JAR": ("jar", "tableware"),
    "PLACEMAT": ("placemat", "tableware"),
    "DRINK_COASTER": ("coaster", "tableware"),
    "DRINKING_STRAW": ("drinking straw", "tableware"),
    # small appliances
    "COFFEE_MAKER": ("coffee maker", "small_appliance"),
    "TOASTER": ("toaster", "small_appliance"),
    "FOOD_BLENDER": ("blender", "small_appliance"),
    "JUICER": ("juicer", "small_appliance"),
    "MICROWAVE_OVEN": ("microwave oven", "small_appliance"),
    "AIR_FRYER": ("air fryer", "small_appliance"),
    "SLOW_COOKER": ("slow cooker", "small_appliance"),
    "RICE_COOKERS": ("rice cooker", "small_appliance"),
    "ELECTRIC_WATER_BOILER": ("electric kettle", "small_appliance"),
    "FOOD_PROCESSOR": ("food processor", "small_appliance"),
    "FOOD_MIXER": ("stand mixer", "small_appliance"),
    "DEEP_FRYER": ("deep fryer", "small_appliance"),
    "COUNTERTOP_OVEN": ("countertop oven", "small_appliance"),
    "BREAD_MAKING_MACHINE": ("bread maker", "small_appliance"),
    # large appliances and climate
    "REFRIGERATOR": ("refrigerator", "large_appliance"),
    "DISHWASHER": ("dishwasher", "large_appliance"),
    "WASHER_DRYER_COMBINATION": ("washing machine", "large_appliance"),
    "AIR_CONDITIONER": ("air conditioner", "large_appliance"),
    "VACUUM_CLEANER": ("vacuum cleaner", "large_appliance"),
    "ROBOTIC_VACUUM_CLEANER": ("robot vacuum", "large_appliance"),
    "DEHUMIDIFIER": ("dehumidifier", "large_appliance"),
    "HUMIDIFIER": ("humidifier", "large_appliance"),
    "AIR_PURIFIER": ("air purifier", "large_appliance"),
    "ELECTRIC_FAN": ("electric fan", "large_appliance"),
    "TELEVISION": ("television", "large_appliance"),
    # home decor
    "WALL_ART": ("wall art print", "home_decor"),
    "HOME_MIRROR": ("mirror", "home_decor"),
    "CLOCK": ("clock", "home_decor"),
    "RUG": ("rug", "home_decor"),
    "RUG_PAD": ("rug pad", "home_decor"),
    "PICTURE_FRAME": ("picture frame", "home_decor"),
    "FIGURINE": ("figurine", "home_decor"),
    "SCULPTURE": ("sculpture", "home_decor"),
    "BOOKEND": ("bookend", "home_decor"),
    "PLANTER": ("planter", "home_decor"),
    "ARTIFICIAL_PLANT": ("artificial plant", "home_decor"),
    "ARTIFICIAL_TREE": ("artificial tree", "home_decor"),
    "CURTAIN": ("curtain", "home_decor"),
    "WINDOW_SHADE": ("window shade", "home_decor"),
    "VASE": ("vase", "home_decor"),
    "BASKET": ("basket", "home_decor"),
    "STICKER_DECAL": ("wall decal", "home_decor"),
    "INCENSE": ("incense", "home_decor"),
    # tools
    "WRENCH": ("wrench", "tools"),
    "SCREWDRIVER": ("screwdriver", "tools"),
    "PLIERS": ("pliers", "tools"),
    "DRILL": ("power drill", "tools"),
    "DRILL_BITS": ("drill bits", "tools"),
    "UTILITY_KNIFE": ("utility knife", "tools"),
    "MULTITOOL": ("multitool", "tools"),
    "SAW_BLADE": ("saw blade", "tools"),
    "LADDER": ("ladder", "tools"),
    "PORTABLE_TOOL_BOX": ("tool box", "tools"),
    "PAINT_BRUSH": ("paint brush", "tools"),
    "SHOVEL_SPADE": ("shovel", "tools"),
    "TAPE_MEASURE": ("tape measure", "tools"),
    # hardware and fittings
    "HARDWARE_HANDLE": ("cabinet handle", "hardware"),
    "HARDWARE_HINGE": ("hinge", "hardware"),
    "LOCK": ("padlock", "hardware"),
    "DOORSTOP": ("door stop", "hardware"),
    "STORAGE_HOOK": ("wall hook", "hardware"),
    "FAUCET": ("faucet", "bath_hardware"),
    "SHOWERHEAD": ("shower head", "bath_hardware"),
    "TOILET_SEAT": ("toilet seat", "bath_hardware"),
    "TOILET_PAPER_HOLDER": ("toilet paper holder", "bath_hardware"),
    "TOOTHBRUSH_HOLDER": ("toothbrush holder", "bath_hardware"),
    "PAPER_TOWEL_HOLDER": ("paper towel holder", "bath_hardware"),
    "PLUMBING_FIXTURE": ("plumbing fixture", "bath_hardware"),
    # office and stationery
    "WRITING_INSTRUMENT": ("pen", "office"),
    "MARKING_PEN": ("marker pen", "office"),
    "FILE_FOLDER": ("file folder", "office"),
    "STORAGE_BINDER": ("ring binder", "office"),
    "ENVELOPE": ("envelope", "office"),
    "STAPLER": ("stapler", "office"),
    "SCISSORS": ("scissors", "office"),
    "LABEL": ("label sheet", "office"),
    "PRINT_COPY_PAPER": ("printer paper", "office"),
    "WRITING_BOARD": ("whiteboard", "office"),
    "CARD_STOCK": ("card stock", "office"),
    "SELF_STICK_NOTE": ("sticky notes", "office"),
    "PINBOARD": ("pin board", "office"),
    "SHIPPING_BOX": ("shipping box", "office"),
    # worn accessories
    "HAT": ("hat", "worn_accessory"),
    "EYEWEAR": ("eyeglasses", "worn_accessory"),
    "SUNGLASSES": ("sunglasses", "worn_accessory"),
    "UMBRELLA": ("umbrella", "worn_accessory"),
    "EARMUFF": ("ear muffs", "worn_accessory"),
    "SWEATBAND": ("sweatband", "worn_accessory"),
    "NECKTIE": ("necktie", "worn_accessory"),
    "VEST": ("vest", "worn_accessory"),
    "OVERALLS": ("overalls", "worn_accessory"),
    "LEOTARD": ("leotard", "worn_accessory"),
    "TRACK_SUIT": ("track suit", "worn_accessory"),
    "SALWAR_SUIT_SET": ("salwar suit", "worn_accessory"),
    "HAIRBAND": ("hair band", "worn_accessory"),
    "SUSPENDER": ("suspenders", "worn_accessory"),
    "SLEEP_MASK": ("sleep mask", "worn_accessory"),
    # cleaning and laundry
    "TRASH_CAN": ("trash can", "cleaning"),
    "LAUNDRY_HAMPER": ("laundry hamper", "cleaning"),
    "BROOM": ("broom", "cleaning"),
    "BUCKET": ("bucket", "cleaning"),
    "CLEANING_BRUSH": ("cleaning brush", "cleaning"),
    "DRYING_RACK": ("drying rack", "cleaning"),
    "CLOTHES_HANGER": ("clothes hanger", "cleaning"),
    "LITTER_BOX": ("litter box", "pet"),
    # fitness and sport
    "EXERCISE_MAT": ("exercise mat", "fitness"),
    "EXERCISE_BAND": ("resistance band", "fitness"),
    "BARBELL": ("barbell", "fitness"),
    "MUSCLE_ROLLER": ("foam roller", "fitness"),
    "STATIONARY_BICYCLE": ("exercise bike", "fitness"),
    "FITNESS_BENCH": ("weight bench", "fitness"),
    "ROWING_MACHINE": ("rowing machine", "fitness"),
    "TREADMILL": ("treadmill", "fitness"),
    "PUNCHING_BAG": ("punching bag", "fitness"),
    "BOXING_GLOVE": ("boxing glove", "fitness"),
    "RECREATION_BALL": ("sports ball", "fitness"),
    "SKATEBOARD": ("skateboard", "fitness"),
    "SPORT_RACKET": ("sports racket", "fitness"),
    "KICK_SCOOTER": ("kick scooter", "fitness"),
    "WALKING_STICK": ("walking stick", "fitness"),
    # personal care implements
    "TOOTHBRUSH": ("toothbrush", "personal_care"),
    "HAIR_BRUSH": ("hair brush", "personal_care"),
    "HAIR_COMB": ("comb", "personal_care"),
    "HAIR_IRON": ("hair straightener", "personal_care"),
    "MANUAL_SHAVING_RAZOR": ("razor", "personal_care"),
    "COSMETIC_BRUSH": ("makeup brush", "personal_care"),
    "MASSAGER": ("massager", "personal_care"),
    "PERSONAL_PILL_DISPENSER": ("pill organiser", "personal_care"),
    "WEIGH_SCALE": ("weighing scale", "personal_care"),
    "THERMOMETER": ("thermometer", "personal_care"),
    # optics and camera
    "CAMERA_TRIPOD": ("camera tripod", "optics"),
    "CAMERA_LENS_FILTERS": ("lens filter", "optics"),
    "BINOCULAR": ("binoculars", "optics"),
    "TELESCOPE": ("telescope", "optics"),
    "MICROSCOPES": ("microscope", "optics"),
    "CAMERA_FLASH": ("camera flash", "optics"),
    "CAMCORDER": ("camcorder", "optics"),
    # outdoor
    "TENT": ("tent", "outdoor"),
    "SLEEPING_BAG": ("sleeping bag", "outdoor"),
    "ICE_CHEST": ("cooler box", "outdoor"),
    "FREESTANDING_SHELTER": ("canopy shelter", "outdoor"),
    "BARBECUE_GRILL": ("barbecue grill", "outdoor"),
    "FOUNTAIN": ("garden fountain", "outdoor"),
    "WILDLIFE_FEEDER": ("bird feeder", "outdoor"),
    "PORTABLE_STOVE": ("portable stove", "outdoor"),
    # pets
    "ANIMAL_COLLAR": ("pet collar", "pet"),
    "PET_TOY": ("pet toy", "pet"),
    "PET_APPAREL": ("pet clothing", "pet"),
    # safety
    "SAFETY_GLASSES": ("safety glasses", "safety"),
    "EARPLUG": ("ear plugs", "safety"),
    "FIRST_AID_KIT": ("first aid kit", "safety"),
    "SAFE": ("security safe", "safety"),
    "ORTHOPEDIC_BRACE": ("orthopaedic brace", "safety"),
    # automotive
    "STEERING_WHEEL_COVER": ("steering wheel cover", "auto"),
    "VEHICLE_SEAT_COVER": ("car seat cover", "auto"),
    "VEHICLE_INTERIOR_SHADE": ("car sun shade", "auto"),
    "LICENSE_PLATE_ATTACHMENT": ("licence plate frame", "auto"),
    "WHEEL": ("wheel", "auto"),
    "VEHICLE_MIRROR": ("car mirror", "auto"),
    "INFANT_TODDLER_CAR_SEAT": ("child car seat", "auto"),
    # toys and games
    "TOY_FIGURE": ("toy figure", "toy"),
    "TOY_BUILDING_BLOCK": ("building blocks", "toy"),
    "PUZZLES": ("jigsaw puzzle", "toy"),
    "TABLETOP_GAME": ("board game", "toy"),
    "GAME_DICE": ("dice", "toy"),
    "NON_RIDING_TOY_VEHICLE": ("toy vehicle", "toy"),
    "CHILDRENS_COSTUME": ("costume", "toy"),
    "STROLLER": ("stroller", "toy"),
    "PACIFIER": ("pacifier", "toy"),
    "BABY_BOTTLE": ("baby bottle", "toy"),
    # musical instruments
    "GUITARS": ("guitar", "instrument"),
    "STRINGED_INSTRUMENTS": ("stringed instrument", "instrument"),
    "PERCUSSION_INSTRUMENTS": ("percussion instrument", "instrument"),
    # general electronics
    "BATTERY": ("battery", "electronics"),
    "CHARGING_ADAPTER": ("charging adapter", "electronics"),
    "ELECTRONIC_ADAPTER": ("electronic adapter", "electronics"),
    "POWER_STRIP": ("power strip", "electronics"),
    "ELECTRONIC_CABLE": ("cable", "electronics"),
    "REMOTE_CONTROL": ("remote control", "electronics"),
    "ANTENNA": ("antenna", "electronics"),
    "SECURITY_CAMERA": ("security camera", "electronics"),
    "NETWORKING_ROUTER": ("wifi router", "electronics"),
    "FLAT_SCREEN_DISPLAY_MOUNT": ("tv wall mount", "electronics"),
    "VIDEO_PROJECTOR": ("video projector", "electronics"),
    "LANDLINE_PHONE": ("landline telephone", "electronics"),
    "CELLULAR_PHONE": ("mobile phone", "electronics"),
    "POWER_CONVERTER": ("power converter", "electronics"),
    "TIMER": ("kitchen timer", "electronics"),
    "MECHANICAL_LIGHTER": ("lighter", "electronics"),
}

# product labels a catalogue photo does not reliably separate: never each other's
# distractor. (Substring pairs such as "shoe"/"athletic shoe" are caught
# automatically by the token-subset rule in the converter.)
PRODUCT_CONFUSABLE = [
    {"suitcase", "luggage", "carrying case"},
    {"phone stand", "phone mount"},
    {"phone case", "tablet case"},
    {"loudspeaker", "computer speaker"},
    {"lamp", "light fixture"},
    {"shelf unit", "storage rack"},
    {"cabinet", "dresser", "storage drawer"},
    {"bed", "bed frame", "mattress"},
    {"eyeglasses", "sunglasses"},
    {"pen", "marker pen"},
    {"plate", "bowl", "dinnerware set"},
    {"rug", "rug pad"},
    {"figurine", "sculpture"},
    {"artificial plant", "artificial tree"},
    {"curtain", "window shade"},
    {"table", "desk"},
    {"stool", "ottoman"},
    {"blanket", "bed sheet"},
    {"handbag", "tote bag"},
    {"ring", "bracelet"},
    {"baking pan", "sheet pan", "roasting pan", "casserole dish"},
    {"frying pan", "dutch oven"},
    {"metal", "steel"},
    {"cable", "charging adapter", "electronic adapter"},
    {"microscope", "telescope"},
    {"hair brush", "comb", "cleaning brush", "paint brush", "makeup brush"},
    {"storage rack", "drying rack", "clothes rack", "bottle rack"},
]

# --- colour -------------------------------------------------------------------
# ABO's `color.standardized_values` is already a small controlled vocabulary; this
# only folds spelling variants together. Compound values ("gold/rose/silver",
# "cyan blue / grey") and junk ("ok", "iphone 11 pro") are simply not in the map,
# so the listing is dropped.
COLOR_MAP = {
    "black": "black", "carbon black": "black", "matte black": "black",
    "white": "white", "bright white": "white", "soft white": "white",
    "off-white": "off-white", "cream": "off-white", "ivory": "ivory",
    "blue": "blue", "navy blue": "navy blue", "navy": "navy blue",
    "light blue": "light blue", "sky blue": "light blue",
    "dark blue": "navy blue", "midnight blue": "navy blue",
    "marine blue": "navy blue", "royal blue": "blue", "smoke blue": "blue",
    "red": "red", "burgundy": "burgundy", "claret": "burgundy",
    "green": "green", "dark green": "green", "pine green": "green",
    "yellow": "yellow", "orange": "orange", "purple": "purple",
    "pink": "pink", "brown": "brown", "dark brown": "brown", "mocha": "brown",
    "grey": "grey", "gray": "grey", "dark grey": "grey",
    "beige": "beige", "sand": "beige", "tan": "tan",
    "silver": "silver", "pewter": "silver", "gold": "gold",
    "bronze": "bronze", "copper": "copper", "terracotta": "terracotta",
    "turquoise": "turquoise", "clear": "transparent", "transparent": "transparent",
    "multi-colored": "multicoloured", "multi": "multicoloured",
    "multicolour": "multicoloured", "multicoloured": "multicoloured",
    "multi-coloured": "multicoloured", "multicolor": "multicoloured",
}
# colours a photo genuinely distinguishes, used as the distractor pool
COLOR_POOL = ["black", "white", "off-white", "ivory", "blue", "navy blue",
              "light blue", "red", "burgundy", "green", "yellow", "orange",
              "purple", "pink", "brown", "grey", "beige", "tan", "silver",
              "gold", "bronze", "copper", "terracotta", "turquoise",
              "transparent", "multicoloured"]
# pairs too close to be forced apart by a photo: never each other's distractor
COLOR_CONFUSABLE = [
    {"white", "off-white", "ivory", "beige", "cream"},
    {"grey", "silver"}, {"gold", "bronze", "copper"},
    {"blue", "navy blue", "light blue", "turquoise"},
    {"red", "burgundy"}, {"brown", "tan"},
    {"multicoloured"}, {"transparent"},
]

# --- material -----------------------------------------------------------------
MATERIAL_MAP = {
    "plastic": "plastic", "abs plastic": "plastic", "hard plastic": "plastic",
    "polycarbonate": "plastic", "acrylic": "acrylic",
    "silicon": "silicone", "silicone": "silicone", "soft silicone": "silicone",
    "tpu": "silicone",
    "canvas": "canvas", "100% canvas": "canvas",
    "wood": "wood", "solid wood": "wood", "engineered wood": "engineered wood",
    "mdf": "engineered wood", "plywood": "engineered wood", "bamboo": "bamboo",
    "rattan": "rattan", "wicker": "rattan", "cane": "rattan",
    "metal": "metal", "iron": "iron", "cast iron": "iron",
    "steel": "steel", "alloy steel": "steel", "carbon steel": "steel",
    "stainless steel": "stainless steel", "brass": "brass",
    "aluminium": "aluminium", "aluminum": "aluminium", "zinc": "zinc",
    "copper": "copper", "sterling silver": "sterling silver",
    "leather": "leather", "genuine leather": "leather", "top-grain leather": "leather",
    "faux leather": "faux leather", "leatherette": "faux leather",
    "synthetic leather": "faux leather", "pu leather": "faux leather",
    "suede": "suede", "microsuede": "suede", "faux suede": "suede",
    "cotton": "cotton", "100% cotton": "cotton", "egyptian cotton": "cotton",
    "denim": "denim", "linen": "linen", "wool": "wool", "felt": "felt",
    "polyester": "polyester", "100% polyester": "polyester",
    "microfiber": "polyester", "velvet": "velvet", "silk": "silk",
    "mesh": "mesh", "fabric": "fabric", "textile": "fabric", "jute": "jute",
    "glass": "glass", "tempered glass": "glass", "crystal": "glass",
    "ceramic": "ceramic", "porcelain": "porcelain", "stoneware": "stoneware",
    "stone": "stone", "marble": "marble", "granite": "granite",
    "concrete": "concrete", "cement": "concrete",
    "rubber": "rubber", "foam": "foam", "memory foam": "foam",
    "paper": "paper", "cardboard": "cardboard", "cork": "cork",
    "nylon": "nylon", "polypropylene": "polypropylene", "pvc vinyl": "vinyl",
    "vinyl": "vinyl", "melamine": "melamine",
}
MATERIAL_POOL = sorted(set(MATERIAL_MAP.values()))
MATERIAL_CONFUSABLE = [
    {"plastic", "acrylic", "silicone", "melamine", "polypropylene", "vinyl", "nylon"},
    {"metal", "steel", "stainless steel", "iron", "aluminium", "zinc", "brass",
     "copper", "sterling silver"},
    {"wood", "engineered wood", "bamboo", "rattan", "cork"},
    {"leather", "faux leather", "suede"},
    {"cotton", "linen", "fabric", "polyester", "canvas", "denim", "mesh",
     "wool", "felt", "velvet", "silk", "jute"},
    {"ceramic", "porcelain", "stoneware", "glass"},
    {"stone", "marble", "granite", "concrete"},
    {"paper", "cardboard"},
    {"foam", "rubber"},
]

# --- pattern ------------------------------------------------------------------
PATTERN_MAP = {
    "solid": "solid", "plain": "solid", "plain-coloured": "solid",
    "plain colored": "solid", "solid color": "solid", "solid colour": "solid",
    "striped": "striped", "stripe": "striped", "stripes": "striped",
    "pinstripe": "striped",
    "floral": "floral", "flower": "floral", "flowers": "floral",
    "geometric": "geometric", "geometric-pattern": "geometric",
    "geometrical": "geometric", "chevron": "chevron", "trellis": "trellis",
    "plaid": "plaid", "tartan": "plaid", "checkered": "checked",
    "checked": "checked", "check": "checked", "houndstooth": "houndstooth",
    "polka dot": "polka dot", "polka dots": "polka dot", "dots": "polka dot",
    "animal": "animal print", "animal print": "animal print",
    "leopard": "animal print", "camouflage": "camouflage", "camo": "camouflage",
    "paisley": "paisley", "damask": "damask", "medallion": "medallion",
    "ikat": "ikat", "moroccan": "moroccan", "herringbone": "herringbone",
    "abstract": "abstract", "textured": "textured", "cable": "cable knit",
    "color block": "colour block", "colour block": "colour block",
    "bordered": "bordered", "marble": "marble",
}
PATTERN_POOL = sorted(set(PATTERN_MAP.values()))
PATTERN_CONFUSABLE = [
    {"plaid", "checked", "houndstooth"},
    {"geometric", "chevron", "trellis", "abstract", "moroccan", "ikat", "damask",
     "medallion", "herringbone"},
    {"solid", "textured", "colour block", "bordered"},
]

# --- item shape ---------------------------------------------------------------
SHAPE_MAP = {
    "rectangular": "rectangular", "rectangle": "rectangular",
    "rectanglular": "rectangular", "rectangular shape": "rectangular",
    "round": "round", "circular": "round", "circle": "round",
    "square": "square", "oval": "oval", "heart": "heart",
    "triangular": "triangular", "triangle": "triangular",
    "hexagonal": "hexagonal", "hexagon": "hexagonal",
    "octagonal": "octagonal", "star": "star",
    "cylindrical": "cylindrical", "cylinder": "cylindrical",
    "teardrop": "teardrop", "l-shape": "l-shaped", "l-shaped": "l-shaped",
    "u-shape": "u-shaped", "u-shaped": "u-shaped", "runner": "runner",
    "drum": "drum", "trapezoid": "trapezoid",
}
SHAPE_POOL = sorted(set(SHAPE_MAP.values()))
SHAPE_CONFUSABLE = [{"round", "oval", "cylindrical", "drum"},
                    {"rectangular", "square", "runner", "trapezoid"}]

# --- finish -------------------------------------------------------------------
FINISH_MAP = {
    "brushed": "brushed", "matte": "matte", "matt": "matte",
    "polished": "polished", "glossy": "glossy", "high-gloss": "glossy",
    "gloss": "glossy", "satin": "satin", "antique": "antique",
    "antiqued": "antique", "distressed": "distressed", "chrome": "chrome",
    "polished chrome": "chrome", "mirror": "mirrored", "mirrored": "mirrored",
    "painted": "painted", "enamel": "enamelled", "enamelled": "enamelled",
    "laminated": "laminated", "natural": "natural",
    "oil rubbed": "oil-rubbed", "oil-rubbed": "oil-rubbed",
    "oil_rubbed_bronze": "oil-rubbed", "wood_grain": "wood grain",
    "wood grain": "wood grain",
}
FINISH_POOL = sorted(set(FINISH_MAP.values()))
FINISH_CONFUSABLE = [{"matte", "satin", "natural"},
                     {"polished", "glossy", "chrome", "mirrored"},
                     {"antique", "distressed", "oil-rubbed"}]

# --- style --------------------------------------------------------------------
# `style` is 5,327 mostly-unusable free-text values. Only silhouettes that a
# photograph actually shows are kept, and only for footwear and bags.
STYLE_MAP = {
    "running shoes": "running shoe", "running shoe": "running shoe",
    "walking shoes": "walking shoe", "sneakers": "sneaker",
    "low-top sneakers": "sneaker", "low-top": "sneaker",
    "high-top sneakers": "high-top sneaker", "high-top": "high-top sneaker",
    "loafers": "loafer", "loafer": "loafer", "penny loafer": "loafer",
    "derby": "derby shoe", "oxford": "oxford shoe", "brogue": "brogue",
    "chelsea boots": "chelsea boot", "chelsea boot": "chelsea boot",
    "ankle boots": "ankle boot", "ankle boot": "ankle boot",
    "knee-high boots": "knee-high boot", "combat boots": "combat boot",
    "ballet flats": "ballet flat", "knit ballet flat": "ballet flat",
    "ballet flat": "ballet flat",
    "flip-flops": "flip-flop", "flip flops": "flip-flop",
    "slippers": "slipper", "slipper": "slipper",
    "closed-toe pumps": "pump", "pumps": "pump", "pump": "pump",
    "wedge": "wedge", "wedges": "wedge",
    "ankle-strap": "ankle-strap sandal", "slide": "slide sandal",
    "slides": "slide sandal", "slip on": "slip-on shoe",
    "slip-on": "slip-on shoe", "mule": "mule", "mules": "mule",
    "espadrille": "espadrille", "espadrilles": "espadrille",
    "clutch": "clutch bag", "tote": "tote bag", "satchel": "satchel bag",
    "crossbody": "crossbody bag", "hobo": "hobo bag",
    "shoulder bag": "shoulder bag", "backpack": "backpack",
}
STYLE_POOL = sorted(set(STYLE_MAP.values()))
STYLE_CONFUSABLE = [
    {"loafer", "derby shoe", "oxford shoe", "brogue", "slip-on shoe", "mule"},
    {"sneaker", "high-top sneaker", "running shoe", "walking shoe"},
    {"chelsea boot", "ankle boot", "knee-high boot", "combat boot"},
    {"flip-flop", "slide sandal", "slipper", "ankle-strap sandal"},
    {"pump", "wedge", "ballet flat", "espadrille"},
    {"clutch bag", "tote bag", "satchel bag", "crossbody bag", "hobo bag",
     "shoulder bag", "backpack"},
]
# styles only asked about inside their own product family, so the options stay sane
STYLE_SCOPE = {"footwear": {"running shoe", "walking shoe", "sneaker",
                            "high-top sneaker", "loafer", "derby shoe",
                            "oxford shoe", "brogue", "chelsea boot", "ankle boot",
                            "knee-high boot", "combat boot", "ballet flat",
                            "flip-flop", "slipper", "pump", "wedge",
                            "ankle-strap sandal", "slide sandal", "slip-on shoe",
                            "mule", "espadrille"},
               "bags": {"clutch bag", "tote bag", "satchel bag", "crossbody bag",
                        "hobo bag", "shoulder bag", "backpack"}}
