"""Stage 3 of decision-p2: keep the questions both answerers got right, attach licences, partition, lint against JevBench,
and write records in the decision-v1 schema.

    python scripts/p2/assemble_p2.py --writer data/decision-p2/teacher/writer.jsonl \
        --answers data/decision-p2/teacher/answers-qwen.jsonl data/decision-p2/teacher/answers-gptoss.jsonl \
        --out data/decision-p2/teacher/records.jsonl

Keep rule: a question is kept only when EVERY answerer's parsed value equals the writer's intended value (unknown == unknown).
Soft targets (phase 2c, `--soft-from qwen35`): distribution-mode rows of that answerer (`gen_answer.py --mode distribution`, marked
`mode: "distribution"`) are taken out of the agreement vote and become the soft teacher. A kept question with such a row gets
`target_probs` (renormalised over its labels + "unknown", "unknown" always present) and `rationale`, provided the teacher's argmax
equals the intended answer; an answerable question whose argmax differs is dropped (this includes every row where the teacher puts
more than half its mass on `unknown`). An intended-unknown question whose argmax is not `unknown` keeps its hard target without
`target_probs` (`--soft-unknown-policy keep-hard`, the owner rule: never drop unknown-gold rows) or is dropped (`drop`). A question
without a usable distribution keeps its hard target. The report's `unknown_mass` audits the teacher's mass on `unknown` for questions
whose intended answer is a real option (mean, rows above 0.2 are flagged not dropped, share above 0.5).
Contamination: any record whose document or question shares >= 2 word 8-grams with the JevBench public files is dropped.
Licence: teacher outputs are released under Apache-2.0 (the writer and answerers are Apache-2.0 models; no Jev output, no
JevBench item and no paid API was used); the evidence file and receipt are written next to the records.
"""
from __future__ import annotations
import argparse, collections, datetime as dt, hashlib, json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent)); sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from p2_common import (ANSWERERS, ROOT, WQuestion, WRITER_MODEL, argmax_label, contamination_count, jevbench_public_files, ngrams, project_probs,
                       read_jsonl, reference_ngrams, to_field, value_to_label)
from v1_text.common import stable_partition, verified_license, write_jsonl

SOURCE = "p2_teacher"
CAUSE = {"insufficient_evidence": "insufficient_evidence", "false_premise": "false_premise", "not_listed": "not_listed", "mismatched_reference": "mismatched_reference"}


def write_license_evidence(directory: Path, writer: dict, answerers: dict, reviewed_by: str = "imajev p2 assembler") -> Path:
    """Evidence text + receipt as verified_license requires. Returns the evidence path (absolute)."""
    directory = Path(directory); directory.mkdir(parents=True, exist_ok=True)
    evidence = directory / "TEACHER-OUTPUTS-Apache-2.0.md"
    lines = ["# decision-p2 teacher outputs: licence evidence", "",
             "The documents, questions and answers in `records.jsonl` were generated by open-weight models released under Apache-2.0:", "",
             f"- writer: {writer['repo']} (revision {writer['revision']}), Apache-2.0", ]
    for k, s in sorted(answerers.items()):
        lines.append(f"- answerer `{k}`: {s['repo']} (revision {s['revision']}), Apache-2.0")
    lines += ["", "Model outputs are released by the imajev project under Apache-2.0. No JevBench item, no output of TypeSafe Jev and no paid",
              "API was used to write, answer, filter or select any record. Real companies, brands and people are prohibited by the writer prompt.",
              "Documents are fictional; any resemblance to real records is coincidental.", ""]
    evidence.write_text("\n".join(lines))
    receipt = {"evidence_sha256": hashlib.sha256(evidence.read_bytes()).hexdigest(), "spdx": "Apache-2.0", "commercial_use_reviewed": True,
               "reviewed_at": dt.date.today().isoformat(), "reviewed_by": reviewed_by,
               "scope": "Synthetic documents, typed questions and teacher answers generated for decision-p2.",
               "source_url": f"https://huggingface.co/{writer['repo']}",
               "review_note": "Generated content from Apache-2.0 models, released under Apache-2.0 by the project; no third-party text is reproduced."}
    evidence.with_name(evidence.name + ".receipt.json").write_text(json.dumps(receipt, indent=2) + "\n")
    return evidence


HEDGES = ("cannot be determined", "can't be determined", "not stated", "not specified", "insufficient", "not enough information",
          "does not say", "doesn't say", "unclear", "ambiguous", "not provided", "no information", "cannot tell", "not possible to determine")


def hedged(raw: str | None) -> bool:
    """True when an answerer's raw text hedges (it answered but said the document does not settle it)."""
    text = (raw or "").lower()
    return any(h in text for h in HEDGES)


def document_text(doc) -> str:
    return doc if isinstance(doc, str) else json.dumps(doc, sort_keys=True)


class NearDuplicateIndex:
    """Inverted index of word 8-grams -> document ids, for the near-duplicate lint (>= threshold shared 8-grams)."""

    def __init__(self, threshold: int = 5, n: int = 8):
        self.threshold, self.n, self.index, self.sizes = threshold, n, collections.defaultdict(set), {}

    def add(self, doc_id: str, text: str) -> None:
        grams = ngrams(text, self.n); self.sizes[doc_id] = len(grams)
        for g in grams:
            self.index[g].add(doc_id)

    def hits(self, text: str) -> tuple[int, str | None]:
        """(max shared 8-grams with any indexed document, that document's id)."""
        counts = collections.Counter()
        for g in ngrams(text, self.n):
            for d in self.index.get(g, ()):
                counts[d] += 1
        if not counts:
            return 0, None
        d, c = counts.most_common(1)[0]
        return c, d

    def is_duplicate(self, text: str) -> tuple[bool, int, str | None]:
        c, d = self.hits(text)
        return c >= self.threshold, c, d

    @classmethod
    def from_files(cls, paths, exclude_ids: set | None = None, threshold: int = 5) -> "NearDuplicateIndex":
        """Writer files contribute output.document; record files contribute request.state (one entry per source_group)."""
        idx = cls(threshold); seen = set()
        for path in paths:
            for r in read_jsonl(Path(path)):
                if "output" in r and "doc_id" in r:
                    did, text = r["doc_id"], document_text(r["output"]["document"])
                elif "request" in r:
                    did, text = f"rec:{r.get('source_group', r.get('id'))}", document_text(r["request"].get("state", ""))
                else:
                    continue
                if did in seen or (exclude_ids and did in exclude_ids):
                    continue
                seen.add(did); idx.add(did, text)
        return idx


def agreement(answers_by_key: dict, key: tuple, intended, n_answerers: int, unknown_rule: str = "strict") -> tuple[bool, list]:
    """strict: every answerer's parsed value equals the intended value (unknown == unknown).

    relaxed (intended unknown only): at least one answerer says unknown (parsed None with no parse error) AND no other answerer
    gives a CONFIDENT non-unknown answer, where confident means parsed to a real value without hedging language in its raw text.
    Answerable questions always use the strict rule."""
    rows = answers_by_key.get(key, [])
    if len(rows) < n_answerers:
        return False, rows
    if intended is None and unknown_rule == "relaxed":
        says_unknown = [r for r in rows if r.get("parse_error") is None and r.get("value") is None]
        if not says_unknown:
            return False, rows
        for r in rows:
            if r.get("value") is not None and not hedged(r.get("raw")):
                return False, rows
        return True, rows
    return all(r.get("parse_error") is None and r.get("value") == intended for r in rows), rows


UNKNOWN_MASS_FLAG = 0.2   # flagged (kept) when the soft teacher puts more than this on unknown for an answerable question


def split_soft_rows(answers: list[dict], soft_from: str | None) -> tuple[list[dict], list[dict]]:
    """(agreement answers, soft-teacher distribution rows). Without --soft-from every row votes, as before."""
    if not soft_from:
        return answers, []
    soft = [r for r in answers if r.get("mode") == "distribution" and r.get("answerer") == soft_from]
    return [r for r in answers if not (r.get("mode") == "distribution" and r.get("answerer") == soft_from)], soft


def soft_label(field: dict, intended, row: dict | None) -> tuple[str, dict | None, float | None]:
    """Judge one soft-teacher row against the intended answer.
    Returns (status, probs, unknown mass): status in missing | parse_error | agree | disagree."""
    if row is None:
        return "missing", None, None
    if row.get("parse_error") or not row.get("probs"):
        return "parse_error", None, None
    probs, err = project_probs(row["probs"], field)
    if err:
        return "parse_error", None, None
    status = "agree" if argmax_label(probs, field) == value_to_label(intended) else "disagree"
    return status, probs, probs["unknown"]


def unknown_mass_audit(masses: list[tuple[str, float]], kept_masses: list[float]) -> dict:
    n = len(masses); over2 = [k for k, m in masses if m > UNKNOWN_MASS_FLAG]; over5 = [k for k, m in masses if m > 0.5]
    return {"answerable_rows": n, "mean": (sum(m for _, m in masses) / n) if n else None,
            "over_0_2": len(over2), "over_0_2_ids": over2[:50], "over_0_5": len(over5), "over_0_5_share": (len(over5) / n) if n else None,
            "kept_rows": len(kept_masses), "kept_mean": (sum(kept_masses) / len(kept_masses)) if kept_masses else None,
            "kept_over_0_2": sum(m > UNKNOWN_MASS_FLAG for m in kept_masses), "kept_over_0_5": sum(m > 0.5 for m in kept_masses),
            "note": f"rows above {UNKNOWN_MASS_FLAG} are flagged (provenance.soft_teacher.unknown_mass_high), not dropped; rows above 0.5 have "
                    "argmax unknown and are dropped by the argmax == intended rule"}


def build_records(writer_rows: list[dict], answers: list[dict], n_answerers: int, license_obj: dict, reference: set, seed: str = "decision-p2",
                  min_shared_ngrams: int = 2, unknown_rule: str = "strict", dedupe: "NearDuplicateIndex | None" = None,
                  soft_from: str | None = None, soft_unknown_policy: str = "keep-hard") -> tuple[list[dict], dict]:
    answers, soft_rows = split_soft_rows(answers, soft_from)
    by_key = collections.defaultdict(list)
    for r in answers:
        by_key[(r["doc_id"], r["qi"])].append(r)
    soft_by_key: dict = {}
    for r in soft_rows:  # a later usable row replaces an earlier one; an error row never replaces a usable one
        k = (r["doc_id"], r["qi"])
        if k not in soft_by_key or not (r.get("parse_error") or not r.get("probs")) or (soft_by_key[k].get("parse_error") or not soft_by_key[k].get("probs")):
            soft_by_key[k] = r
    masses: list[tuple[str, float]] = []; kept_masses: list[float] = []
    counts = collections.Counter(); kept: list[dict] = []; fam_counts = collections.Counter(); fam_kept = collections.Counter()
    dup_pairs: list[tuple[int, str, str]] = []
    for w in writer_rows:
        out = w["output"]; part = stable_partition(w["doc_id"], seed=seed)
        doc_text = out["document"] if isinstance(out["document"], str) else json.dumps(out["document"])
        if dedupe is not None:
            is_dup, shared, other = dedupe.is_duplicate(doc_text)
            if is_dup:
                counts["near_duplicates_dropped"] += 1; counts["questions"] += len(out["questions"])
                counts["near_duplicate_questions_dropped"] += len(out["questions"]); dup_pairs.append((shared, w["doc_id"], other)); continue
            dedupe.add(w["doc_id"], doc_text)  # earlier documents in the same batch count too
        doc_hits = contamination_count(doc_text, reference)
        for qi, q in enumerate(out["questions"]):
            counts["questions"] += 1; fam_counts[q["family"]] += 1
            field, intended = to_field(WQuestion.model_validate(q), field_id="decision")
            soft_status, soft_probs, soft_unknown = "off", None, None
            if soft_from:
                soft_row = soft_by_key.get((w["doc_id"], qi))
                soft_status, soft_probs, soft_unknown = soft_label(field, intended, soft_row)
                if intended is not None and soft_unknown is not None:
                    masses.append((f"{SOURCE}:{w['doc_id']}:{qi}", soft_unknown))
            ok, rows = agreement(by_key, (w["doc_id"], qi), intended, n_answerers, unknown_rule)
            if len(rows) < n_answerers or (soft_from and n_answerers == 0 and soft_status in ("missing", "parse_error")):
                counts["missing_answers"] += 1; continue
            if not ok:
                counts["disagreed"] += 1; continue
            if soft_status == "disagree":
                if intended is None and soft_unknown_policy == "keep-hard":
                    counts["soft_disagreed_unknown_kept_hard"] += 1; soft_status, soft_probs = "disagree_kept_hard", None
                else:
                    counts["soft_disagreed"] += 1; continue
            if doc_hits + contamination_count(q["question"], reference) >= min_shared_ngrams:
                counts["contaminated"] += 1; continue
            unknown = intended is None
            rec = {"id": f"{SOURCE}:{w['doc_id']}:{qi}", "source": SOURCE, "source_split": "teacher", "source_group": w["doc_id"], "partition": part,
                   "family": q["family"], "domain": w["plan"]["domain"], "batch": w.get("batch", w["plan"].get("batch", "p2")),
                   "heldout_family": False, "license": license_obj, "images": [],
                   "request": {"schema_version": "1.0", "request_id": f"{SOURCE}-{w['doc_id']}-{qi}", "state": out["document"], "fields": [field]},
                   "target": intended, "abstention_cause": CAUSE[q["unknown_reason"]] if unknown else None,
                   "source_answer": q["intended"], "pseudo_label": "p2-teacher-agreed", "template_id": f"p2.{q['family']}.v1",
                   "unknown_by_construction": {"decision": unknown}, "state_variant": w["plan"]["state_shape"],
                   "provenance": {"writer": w["writer"], "answerers": [{k: r.get(k) for k in ("answerer", "repo", "revision", "value", "confidence")} for r in rows],
                                  "agreement": True, "unknown_rule": unknown_rule if unknown else "strict", "justification": q["justification"]}}
            if soft_from:
                counts[f"soft_{soft_status}"] += 1
                srow = soft_by_key.get((w["doc_id"], qi)) or {}
                rec["provenance"]["soft_teacher"] = {"answerer": soft_from, "repo": srow.get("repo"), "revision": srow.get("revision"), "status": soft_status}
                if soft_probs is not None:
                    rec["target_probs"] = soft_probs
                    rationale = srow.get("rationale")
                    if isinstance(rationale, str) and rationale.strip():
                        rec["rationale"] = rationale.strip()
                    rec["provenance"]["soft_teacher"]["unknown_mass"] = soft_unknown
                    if not unknown:
                        kept_masses.append(soft_unknown)
                        rec["provenance"]["soft_teacher"]["unknown_mass_high"] = soft_unknown > UNKNOWN_MASS_FLAG
            kept.append(rec); counts["kept"] += 1; fam_kept[q["family"]] += 1
            if unknown: counts["kept_unknown"] += 1
    counts["writer_docs"] = len(writer_rows)
    report = {"counts": dict(counts), "unknown_share": (counts["kept_unknown"] / counts["kept"]) if counts["kept"] else None,
              "near_duplicate_pairs": [{"shared_8grams": c, "new": a, "existing": b} for c, a, b in sorted(dup_pairs, reverse=True)[:20]],
              "by_family": {f: {"questions": fam_counts[f], "kept": fam_kept[f]} for f in sorted(fam_counts)},
              "by_partition": dict(collections.Counter(r["partition"] for r in kept)),
              "by_type": dict(collections.Counter(r["request"]["fields"][0]["type"] for r in kept)),
              "by_domain": dict(collections.Counter(r["domain"] for r in kept))}
    if soft_from:
        report["soft_from"] = soft_from; report["soft_unknown_policy"] = soft_unknown_policy
        report["with_target_probs"] = sum("target_probs" in r for r in kept); report["with_rationale"] = sum("rationale" in r for r in kept)
        report["unknown_mass"] = unknown_mass_audit(masses, kept_masses)
    return kept, report


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--writer", type=Path, required=True); ap.add_argument("--answers", type=Path, nargs="+", required=True)
    ap.add_argument("--out", type=Path, required=True); ap.add_argument("--license-dir", type=Path)
    ap.add_argument("--reference", type=Path, nargs="*", help="JevBench public files (default: .cache/external/jevbench/datasets/public/*.jsonl)")
    ap.add_argument("--seed", default="decision-p2"); ap.add_argument("--min-unknown-share", type=float, default=0.15)
    ap.add_argument("--unknown-rule", choices=("strict", "relaxed"), default="strict",
                    help="relaxed: keep an intended-unknown question when one answerer says unknown and no other answers confidently")
    ap.add_argument("--batch-filter", default="", help="fnmatch pattern on the writer rows' `batch` (e.g. 'p2b-*'); default: all rows")
    ap.add_argument("--append-to", type=Path, help="existing records file to merge into (ids already present are skipped); written to --out")
    ap.add_argument("--dedupe-against", type=Path, nargs="*", default=None,
                    help="writer.jsonl / records.jsonl files whose documents or states a new document must not near-duplicate "
                         "(default: data/decision-p2/teacher/writer.jsonl and data/decision-p2/human/records.jsonl when present)")
    ap.add_argument("--dedupe-threshold", type=int, default=5, help="shared word 8-grams at or above which a document is a near-duplicate")
    ap.add_argument("--soft-from", default=None, choices=sorted(ANSWERERS),
                    help="answerer whose distribution-mode rows (gen_answer.py --mode distribution, passed in --answers) give target_probs + rationale; "
                         "keep rule: its argmax must equal the intended answer")
    ap.add_argument("--soft-unknown-policy", choices=("keep-hard", "drop"), default="keep-hard",
                    help="intended-unknown questions whose soft argmax is not unknown: keep with the hard target only (default) or drop")
    a = ap.parse_args(argv)
    import fnmatch
    writer_rows = read_jsonl(a.writer); answers = [r for p in a.answers for r in read_jsonl(p)]
    if a.batch_filter:
        writer_rows = [w for w in writer_rows if fnmatch.fnmatch(str(w.get("batch", w.get("plan", {}).get("batch", "p2"))), a.batch_filter)]
        wanted = {w["doc_id"] for w in writer_rows}; answers = [r for r in answers if r["doc_id"] in wanted]
    n_answerers = len({r["answerer"] for r in split_soft_rows(answers, a.soft_from)[0]})
    license_dir = a.license_dir or (ROOT / "data/decision-p2/licenses" / SOURCE)
    evidence = write_license_evidence(license_dir, WRITER_MODEL, ANSWERERS)
    rel = evidence.relative_to(ROOT) if evidence.is_relative_to(ROOT) else evidence
    license_obj = verified_license(Path(rel), "Apache-2.0")
    reference = reference_ngrams(a.reference if a.reference is not None else jevbench_public_files())
    dedupe_paths = a.dedupe_against if a.dedupe_against is not None else [q for q in (ROOT / "data/decision-p2/teacher/writer.jsonl", ROOT / "data/decision-p2/human/records.jsonl") if q.is_file()]
    batch_ids = {w["doc_id"] for w in writer_rows}
    dedupe = NearDuplicateIndex.from_files(dedupe_paths, exclude_ids=batch_ids, threshold=a.dedupe_threshold) if dedupe_paths else NearDuplicateIndex(a.dedupe_threshold)
    kept, report = build_records(writer_rows, answers, n_answerers, license_obj, reference, seed=a.seed, unknown_rule=a.unknown_rule, dedupe=dedupe,
                                 soft_from=a.soft_from, soft_unknown_policy=a.soft_unknown_policy)
    report["dedupe_files"] = [str(q) for q in dedupe_paths]; report["dedupe_threshold"] = a.dedupe_threshold
    # Every record must pass the serving contract (state nesting <= 8, sizes, option counts) or it crashes the trainer's loader.
    sys.path.insert(0, str(ROOT / "src")); from decision_data import expand_fields, render
    valid, contract_dropped = [], collections.Counter()
    for r in kept:
        try:
            for item in expand_fields(r): render(item, soft_targets="target_probs" in item)
            valid.append(r)
        except Exception as exc:
            contract_dropped[(str(exc).split("\n")[1] if "\n" in str(exc) else str(exc))[:60]] += 1
    if contract_dropped: print("contract validation dropped", sum(contract_dropped.values()), dict(contract_dropped))
    kept = valid
    if a.append_to is not None and a.append_to.is_file():
        existing = read_jsonl(a.append_to); have = {r["id"] for r in existing}
        new_rows = [r for r in kept if r["id"] not in have]
        report["appended_to"] = str(a.append_to); report["existing_records"] = len(existing); report["new_records"] = len(new_rows)
        kept = existing + new_rows
    write_jsonl(a.out, kept)
    report["reference_ngrams"] = len(reference); report["answerers"] = n_answerers; report["records"] = len(kept)
    report["manifest_sha256"] = hashlib.sha256(a.out.read_bytes()).hexdigest()
    a.out.with_name("assembly-report.json").write_text(json.dumps(report, indent=2) + "\n")
    readme = [f"# decision-p2 teacher records", "", f"{len(kept)} kept questions from {report['counts'].get('writer_docs', 0)} writer documents; "
              f"{report['counts'].get('disagreed', 0)} dropped by answerer disagreement, {report['counts'].get('contaminated', 0)} by JevBench 8-gram overlap, "
              f"{report['counts'].get('missing_answers', 0)} lacked answers; {report['counts'].get('near_duplicates_dropped', 0)} documents dropped as near-duplicates.", "",
              f"Unknown share: {report['unknown_share']:.1%}" if report['unknown_share'] is not None else "Unknown share: n/a",
              f"Partitions: {report['by_partition']}", f"Types: {report['by_type']}", "",
              "| Family | questions | kept |", "|---|---:|---:|"] + [f"| {f} | {v['questions']} | {v['kept']} |" for f, v in report["by_family"].items()]
    a.out.with_name("README.md").write_text("\n".join(readme) + "\n")
    print(json.dumps({k: report[k] for k in ("counts", "unknown_share", "by_partition", "by_type", "records", "near_duplicate_pairs", "with_target_probs",
                                             "with_rationale", "unknown_mass") if k in report}))
    if report["unknown_share"] is not None and report["unknown_share"] < a.min_unknown_share:
        print(f"WARNING: unknown share {report['unknown_share']:.1%} below {a.min_unknown_share:.0%}; generate more unknown-family documents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
