"""multi_hop: two or three facts in the state that must be chained to reach the answer."""

ITEMS = [
{
 "key": "mh01", "domain": "retail",
 "state": {"order": {"id": "O-5512", "sku": "SKU-771", "quantity": 2, "placed": "2026-04-06"},
           "catalogue": [{"sku": "SKU-770", "product": "ash bookcase", "supplier": "Halvorsen"},
                         {"sku": "SKU-771", "product": "oak side table", "supplier": "Verro"},
                         {"sku": "SKU-772", "product": "walnut stool", "supplier": "Verro"}],
           "suppliers": [{"name": "Halvorsen", "lead_time_days": 6, "ships_from": "Denmark"},
                         {"name": "Verro", "lead_time_days": 12, "ships_from": "Portugal"}],
           "customer_promise": "dispatch within 10 days of the order date",
           "stock_on_hand": {"SKU-770": 4, "SKU-771": 0, "SKU-772": 9}},
 "field": {"id": "meets_promise", "type": "boolean",
           "question": "Will order O-5512 be dispatched inside the 10-day promise?"},
 "target": False, "abstention_cause": None,
 "rationale": "SKU-771 is out of stock and comes from Verro, whose 12-day lead time is longer than the 10-day dispatch promise."},
{
 "key": "mh02", "domain": "hr",
 "state": "Rafe Okonkwo reports into the Atlas engineering team. The manager of the Atlas team is Wen Li. "
          "Wen Li holds grade 3 spending authority. At Broadmere, grade 3 authority covers single requests up to "
          "2,000 EUR; anything above that goes to a grade 4 holder as well. Rafe has submitted an equipment request "
          "for a monitor and dock costing 2,600 EUR in total, on one request form.",
 "field": {"id": "wen_can_approve", "type": "boolean",
           "question": "Can Wen Li approve Rafe's equipment request on her own?"},
 "target": False, "abstention_cause": None,
 "rationale": "Rafe's manager is Wen Li, whose grade 3 authority stops at 2,000 EUR, and the single request is 2,600 EUR, so a grade 4 holder must join her."},
{
 "key": "mh03", "domain": "logistics",
 "state": {"vehicle": {"reg": "HG21 PLX", "route": "R-14", "eta": "2026-05-19T19:40"},
           "routes": [{"id": "R-13", "terminates_at": "Depot North"},
                      {"id": "R-14", "terminates_at": "Depot East"},
                      {"id": "R-15", "terminates_at": "Depot North"}],
           "depots": [{"name": "Depot North", "receiving_hours": "06:00-22:00", "overnight_bay": True},
                      {"name": "Depot East", "receiving_hours": "06:00-19:00", "overnight_bay": False}],
           "rule": "A vehicle arriving after receiving hours at a depot with no overnight bay must divert to the nearest depot that has one."},
 "field": {"id": "must_divert", "type": "boolean",
           "question": "Must vehicle HG21 PLX divert on 19 May?"},
 "target": True, "abstention_cause": None,
 "rationale": "Route R-14 terminates at Depot East, whose receiving hours end at 19:00 and which has no overnight bay, so the 19:40 arrival triggers the diversion rule."},
{
 "key": "mh04", "domain": "healthcare_admin",
 "state": "Mr Halvard is covered by the Coastline Silver plan. The Coastline Silver plan uses the Meridian provider "
          "network. Bayview Orthopaedics is contracted with the Harbour network and with the Summit network, but not "
          "with Meridian. Under the plan, care from a provider outside the plan's network is paid at 50 percent "
          "coinsurance instead of the flat copay.",
 "field": {"id": "flat_copay", "type": "boolean",
           "question": "Will Mr Halvard's visit to Bayview Orthopaedics be charged at the flat copay?"},
 "target": False, "abstention_cause": None,
 "rationale": "Coastline Silver uses Meridian, Bayview is contracted only with Harbour and Summit, so the visit is out of network and falls to 50 percent coinsurance."},
{
 "key": "mh05", "domain": "finance_ops",
 "state": {"invoice": {"number": "INV-3391", "vendor_id": "V-207", "issued": "2026-06-02", "amount_eur": 14500},
           "vendors": [{"id": "V-206", "name": "Calloway Print", "terms": "net 30"},
                       {"id": "V-207", "name": "Stroma Services", "terms": "net 45"},
                       {"id": "V-208", "name": "Ferris Parts", "terms": "net 60"}],
           "terms_definitions": {"net 30": 30, "net 45": 45, "net 60": 60},
           "today": "2026-07-20",
           "note": "Payment is late once the due date has passed."},
 "field": {"id": "is_late", "type": "boolean",
           "question": "Is invoice INV-3391 late as at today's date?"},
 "target": True, "abstention_cause": None,
 "rationale": "Vendor V-207 is Stroma Services on net 45 terms, so the 2 June invoice fell due on 17 July, which is before today's 20 July."},
{
 "key": "mh06", "domain": "software_incidents",
 "state": "The alert 'checkout_latency_p99' fires on the service named payments-gateway. In the service catalogue, "
          "payments-gateway is owned by the Ledger team, and the service basket-api is owned by the Storefront team. "
          "The Ledger team's on-call rota for week 24 lists Amara Bello as primary and Josip Marek as secondary. The "
          "Storefront team's rota for week 24 lists Priya Nair as primary.",
 "field": {"id": "amara_paged", "type": "boolean",
           "question": "If checkout_latency_p99 fires during week 24, is Amara Bello the person paged first?"},
 "target": True, "abstention_cause": None,
 "rationale": "The alert belongs to payments-gateway, which the Ledger team owns, and Amara Bello is the Ledger primary on-call for week 24."},
{
 "key": "mh07", "domain": "travel",
 "state": {"booking": {"reference": "QT77BN", "passenger": "L. Fontaine", "fare_code": "K"},
           "fare_codes": [{"code": "Y", "cabin": "economy", "flexible": True},
                          {"code": "K", "cabin": "economy", "flexible": False},
                          {"code": "D", "cabin": "business", "flexible": True}],
           "lounge_policy": "Lounge access is included for business cabin passengers and for economy passengers "
                            "holding a flexible fare. All other passengers may buy access at the door.",
           "loyalty": {"tier": "none"}},
 "field": {"id": "lounge_included", "type": "boolean",
           "question": "Is lounge access included in this passenger's booking?"},
 "target": False, "abstention_cause": None,
 "rationale": "Fare code K is an economy fare that is not flexible, and with no loyalty tier the policy offers only paid access at the door."},
{
 "key": "mh08", "domain": "education",
 "state": "Ola is enrolled on the BSc Environmental Science programme. That programme's Year 2 module EV240 lists "
          "EV140 Statistics for Scientists as a required prerequisite. Ola's transcript shows EV130 Field Methods "
          "(pass), EV141 Data Handling (pass) and CH110 Chemistry (pass). The department treats a prerequisite as "
          "met only by the exact module code listed, with no substitutions outside a formal waiver, and Ola has no "
          "waiver on file.",
 "field": {"id": "may_take_ev240", "type": "boolean",
           "question": "May Ola register for EV240 next year?"},
 "target": False, "abstention_cause": None,
 "rationale": "EV240 requires EV140 exactly, Ola's transcript shows EV130 and EV141 but not EV140, and no waiver is on file."},
{
 "key": "mh09", "domain": "retail",
 "state": {"return_request": {"id": "RR-8840", "sku": "SKU-914", "reason": "wrong size"},
           "catalogue": [{"sku": "SKU-770", "product": "ash bookcase", "return_window_days": 30},
                         {"sku": "SKU-771", "product": "oak side table", "return_window_days": 30},
                         {"sku": "SKU-802", "product": "cotton throw", "return_window_days": 14}],
           "policy": "The return window depends on the product's catalogue entry. Products absent from the "
                     "catalogue extract below are governed by entries this extract does not contain.",
           "purchased_days_ago": 20},
 "field": {"id": "inside_window", "type": "boolean",
           "question": "Is return request RR-8840 inside its return window?"},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "The window depends on the catalogue entry for SKU-914, and the extract in the state contains no entry for that SKU, so the chain cannot be completed."},
{
 "key": "mh10", "domain": "hr",
 "state": "Dalia has accepted an offer for the role 'Senior Reliability Engineer'. At Vinter Systems that role sits at "
          "grade 6. The relocation policy pays a relocation allowance to new joiners at grade 7 and above, and to "
          "joiners at any grade who are moving from outside the country. Dalia currently lives in the same city as "
          "the office she will join.",
 "field": {"id": "relocation_allowance", "type": "boolean",
           "question": "Does Dalia qualify for the relocation allowance?"},
 "target": False, "abstention_cause": None,
 "rationale": "Her role maps to grade 6, below the grade 7 threshold, and she is not moving from outside the country, so neither route in the policy applies."},
{
 "key": "mh11", "domain": "logistics",
 "state": {"consignment": {"id": "C-2207", "delivery_postcode": "LS9 8TQ"},
           "postcode_zones": [{"prefix": "LS1", "zone": "Leeds Central"}, {"prefix": "LS9", "zone": "Leeds East"},
                              {"prefix": "BD3", "zone": "Bradford"}],
           "zone_depots": [{"zone": "Leeds Central", "depot": "Depot Kirkstall"},
                           {"zone": "Leeds East", "depot": "Depot Seacroft"},
                           {"zone": "Bradford", "depot": "Depot Shipley"}],
           "depot_couriers": [{"depot": "Depot Kirkstall", "courier": "Aldergate Couriers"},
                              {"depot": "Depot Seacroft", "courier": "Beckfield Delivery"},
                              {"depot": "Depot Shipley", "courier": "Cawdor Logistics"}]},
 "field": {"id": "courier", "type": "choice",
           "question": "Which courier will deliver consignment C-2207?",
           "options": [{"value": "Aldergate Couriers"}, {"value": "Beckfield Delivery"},
                       {"value": "Cawdor Logistics"}, {"value": "none of these"}]},
 "target": "Beckfield Delivery", "abstention_cause": None,
 "rationale": "LS9 maps to the Leeds East zone, Leeds East is served by Depot Seacroft, and Depot Seacroft's courier is Beckfield Delivery."},
{
 "key": "mh12", "domain": "healthcare_admin",
 "state": {"referral": {"id": "R-4412", "reason_code": "MSK-07"},
           "reason_codes": [{"code": "MSK-06", "meaning": "shoulder pain, non-traumatic", "speciality": "rheumatology"},
                            {"code": "MSK-07", "meaning": "knee instability after injury", "speciality": "orthopaedics"},
                            {"code": "NEU-02", "meaning": "persistent headache", "speciality": "neurology"}],
           "speciality_clinics": [{"speciality": "rheumatology", "clinic": "Clinic B, Tuesdays"},
                                  {"speciality": "orthopaedics", "clinic": "Clinic D, Thursdays"},
                                  {"speciality": "neurology", "clinic": "Clinic A, Mondays"}]},
 "field": {"id": "clinic", "type": "choice",
           "question": "Which clinic should referral R-4412 be booked into?",
           "options": [{"value": "Clinic A, Mondays"}, {"value": "Clinic B, Tuesdays"},
                       {"value": "Clinic D, Thursdays"}, {"value": "no suitable clinic"}]},
 "target": "Clinic D, Thursdays", "abstention_cause": None,
 "rationale": "Reason code MSK-07 is knee instability, which belongs to orthopaedics, and the orthopaedics clinic is Clinic D on Thursdays."},
{
 "key": "mh13", "domain": "finance_ops",
 "state": {"payment": {"id": "P-9911", "counterparty_id": "CP-42", "amount": 78000},
           "counterparties": [{"id": "CP-41", "name": "Avona Ltd", "country": "IE"},
                              {"id": "CP-42", "name": "Brixen GmbH", "country": "DE"},
                              {"id": "CP-43", "name": "Corvo SA", "country": "CH"}],
           "country_currency": {"IE": "EUR", "DE": "EUR", "CH": "CHF"},
           "settlement_accounts": [{"currency": "EUR", "account": "Nostro EUR-01"},
                                   {"currency": "CHF", "account": "Nostro CHF-02"},
                                   {"currency": "GBP", "account": "Nostro GBP-03"}]},
 "field": {"id": "account", "type": "choice",
           "question": "Which settlement account should payment P-9911 use?",
           "options": [{"value": "Nostro EUR-01"}, {"value": "Nostro CHF-02"},
                       {"value": "Nostro GBP-03"}, {"value": "no account matches"}]},
 "target": "Nostro EUR-01", "abstention_cause": None,
 "rationale": "CP-42 is Brixen GmbH in DE, DE settles in EUR, and the EUR settlement account is Nostro EUR-01."},
{
 "key": "mh14", "domain": "software_incidents",
 "state": {"alert": {"name": "queue_depth_critical", "component": "ingest-worker"},
           "components": [{"name": "ingest-worker", "tier": "data-plane"},
                          {"name": "web-frontend", "tier": "edge"},
                          {"name": "billing-cron", "tier": "control-plane"}],
           "runbooks": [{"tier": "edge", "runbook": "RB-EDGE-1"},
                        {"tier": "data-plane", "runbook": "RB-DATA-4"},
                        {"tier": "control-plane", "runbook": "RB-CTRL-2"}],
           "note": "Each alert is handled with the runbook for its component's tier."},
 "field": {"id": "runbook", "type": "choice",
           "question": "Which runbook applies to queue_depth_critical?",
           "options": [{"value": "RB-EDGE-1"}, {"value": "RB-DATA-4"},
                       {"value": "RB-CTRL-2"}, {"value": "no runbook applies"}]},
 "target": "RB-DATA-4", "abstention_cause": None,
 "rationale": "The alert fires on ingest-worker, which sits in the data-plane tier, and the data-plane runbook is RB-DATA-4."},
{
 "key": "mh15", "domain": "travel",
 "state": "Flight EV442 is operated by Estrel Air. At Rothwell International, Estrel Air and its partners check in at "
          "Terminal 2; all other carriers use Terminal 1. Estrel Air's only partner at Rothwell is Nordgate Airways. "
          "The passenger's connecting flight NG117 is operated by Nordgate Airways from the same airport, and there "
          "is no inter-terminal transfer inside security.",
 "field": {"id": "terminal", "type": "choice",
           "question": "Which terminal should the passenger go to for the NG117 departure?",
           "options": [{"value": "Terminal 1"}, {"value": "Terminal 2"},
                       {"value": "either terminal"}, {"value": "neither terminal"}]},
 "target": "Terminal 2", "abstention_cause": None,
 "rationale": "NG117 is operated by Nordgate Airways, Nordgate is Estrel Air's partner at Rothwell, and partners use Terminal 2."},
{
 "key": "mh16", "domain": "education",
 "state": {"student": {"id": "S-3301", "name": "Behrouz", "seminar_group": "G4"},
           "seminar_groups": [{"group": "G3", "module": "PH210"}, {"group": "G4", "module": "PH215"},
                              {"group": "G5", "module": "PH210"}],
           "module_leads": [{"module": "PH210", "lead": "Dr Farrow"}, {"module": "PH215", "lead": "Dr Iyengar"},
                            {"module": "PH220", "lead": "Dr Novak"}],
           "rule": "An extension request goes to the lead of the module that the student's seminar group studies."},
 "field": {"id": "who_decides", "type": "choice",
           "question": "Who decides Behrouz's extension request?",
           "options": [{"value": "Dr Farrow"}, {"value": "Dr Iyengar"},
                       {"value": "Dr Novak"}, {"value": "the faculty office"}]},
 "target": "Dr Iyengar", "abstention_cause": None,
 "rationale": "Behrouz is in seminar group G4, G4 studies PH215, and the lead of PH215 is Dr Iyengar."},
{
 "key": "mh17", "domain": "retail",
 "state": "The customer has ordered the item 'Kestrel 14 rucksack'. In the product master, the Kestrel 14 rucksack "
          "belongs to the Outdoor category. Outdoor stock is held at the Ramsgill warehouse; Home stock is held at "
          "Ferrybridge and Apparel stock at Aldwick. The Ramsgill warehouse is closed for a stock count from 3 to 5 "
          "June, during which its orders are fulfilled from Ferrybridge if the item is also held there. The Kestrel "
          "14 rucksack is not held at Ferrybridge. The order was placed on 4 June.",
 "field": {"id": "fulfilling_site", "type": "choice",
           "question": "Which site will fulfil this order?",
           "options": [{"value": "Ramsgill, once the stock count ends"}, {"value": "Ferrybridge"},
                       {"value": "Aldwick"}, {"value": "the order cannot be fulfilled at all"}]},
 "target": "Ramsgill, once the stock count ends", "abstention_cause": None,
 "rationale": "The rucksack is Outdoor stock held only at Ramsgill, and the 4 June closure only diverts to Ferrybridge for items Ferrybridge also holds, which this is not."},
{
 "key": "mh18", "domain": "hr",
 "state": {"employee": {"id": "E-118", "job_code": "OPS-3"},
           "job_codes": [{"code": "OPS-2", "title": "Operations Associate", "family": "Operations", "level": 2},
                         {"code": "OPS-3", "title": "Operations Specialist", "family": "Operations", "level": 3},
                         {"code": "FIN-3", "title": "Finance Specialist", "family": "Finance", "level": 3}],
           "pay_bands": [{"family": "Operations", "level": 2, "band": "B2"},
                         {"family": "Operations", "level": 3, "band": "B4"},
                         {"family": "Finance", "level": 3, "band": "B5"}]},
 "field": {"id": "pay_band", "type": "choice",
           "question": "Which pay band does employee E-118 sit in?",
           "options": [{"value": "B2"}, {"value": "B4"}, {"value": "B5"}, {"value": "no band matches"}]},
 "target": "B4", "abstention_cause": None,
 "rationale": "Job code OPS-3 is Operations at level 3, and the Operations level 3 pay band is B4."},
{
 "key": "mh19", "domain": "logistics",
 "state": "Container MSKU4419022 is booked on service loop AE7. Service loop AE7 calls at Rotterdam and then at "
          "Felixstowe. The consignee's inland terminal is Birmingham. Inland terminals in the United Kingdom are "
          "served from Felixstowe; inland terminals in the Netherlands and Germany are served from Rotterdam. "
          "Birmingham is in the United Kingdom.",
 "field": {"id": "discharge_port", "type": "choice",
           "question": "At which port should the container be discharged?",
           "options": [{"value": "Rotterdam"}, {"value": "Felixstowe"},
                       {"value": "either port"}, {"value": "neither port is on the loop"}]},
 "target": "Felixstowe", "abstention_cause": None,
 "rationale": "The consignee's inland terminal is Birmingham, Birmingham is in the United Kingdom, and UK inland terminals are served from Felixstowe."},
{
 "key": "mh20", "domain": "finance_ops",
 "state": {"expense_claim": {"id": "EC-7712", "cost_centre": "CC-884", "amount_gbp": 310},
           "cost_centres": [{"code": "CC-881", "owner": "Marketing", "approver": "H. Adeyemi"},
                            {"code": "CC-882", "owner": "Facilities", "approver": "R. Klaasen"},
                            {"code": "CC-883", "owner": "Legal", "approver": "S. Duarte"}],
           "approval_rule": "A claim is approved by the owner of its cost centre; the cost-centre register below is "
                            "the only source of that mapping and is complete for the codes it lists."},
 "field": {"id": "approver", "type": "choice",
           "question": "Who approves expense claim EC-7712?",
           "options": [{"value": "H. Adeyemi"}, {"value": "R. Klaasen"},
                       {"value": "S. Duarte"}, {"value": "the finance director"}]},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "The approver follows from the cost centre CC-884, and the register in the state lists CC-881 to CC-883 only, so the chain has no second link."},
{
 "key": "mh21", "domain": "travel",
 "state": {"guest": {"name": "T. Aliyev", "rate_plan": "CORP-GOLD"},
           "rate_plans": [{"code": "CORP-STD", "breakfast": False, "late_checkout": False},
                          {"code": "CORP-GOLD", "breakfast": True, "late_checkout": True},
                          {"code": "LEISURE-SAVER", "breakfast": False, "late_checkout": False}],
           "property_rules": "Late checkout under a rate plan is honoured until 14:00, except on days the property "
                             "is at full occupancy, when it is honoured only until 12:00.",
           "occupancy": {"checkout_date": "2026-08-15", "status": "full occupancy"}},
 "field": {"id": "latest_checkout", "type": "choice",
           "question": "What is the latest checkout time this guest is entitled to on 15 August?",
           "options": [{"value": "11:00"}, {"value": "12:00"}, {"value": "14:00"},
                       {"value": "no late checkout at all"}]},
 "target": "12:00", "abstention_cause": None,
 "rationale": "CORP-GOLD includes late checkout, and because the property is at full occupancy on 15 August the entitlement is capped at 12:00."},
{
 "key": "mh22", "domain": "software_incidents",
 "state": "The failing request carries tenant id t-5512. Tenant t-5512 is provisioned in the cell named cell-eu-03. "
          "Cells cell-eu-01 through cell-eu-04 run in the Frankfurt region; cells cell-us-01 and cell-us-02 run in "
          "the Ohio region. Log retention is 30 days in Frankfurt and 14 days in Ohio. The support agent needs logs "
          "from 25 days ago.",
 "field": {"id": "log_availability", "type": "choice",
           "question": "Where should the agent look for the logs, and will they still be there?",
           "options": [{"value": "Frankfurt, and the logs are still retained"},
                       {"value": "Frankfurt, but the logs have been deleted"},
                       {"value": "Ohio, and the logs are still retained"},
                       {"value": "Ohio, but the logs have been deleted"}]},
 "target": "Frankfurt, and the logs are still retained", "abstention_cause": None,
 "rationale": "Tenant t-5512 lives in cell-eu-03, which runs in Frankfurt, and Frankfurt keeps logs for 30 days, so a 25-day-old log is still there."},
{
 "key": "mh23", "domain": "healthcare_admin",
 "state": {"episode": {"id": "EP-2291", "procedure_code": "PR-114"},
           "procedure_codes": [{"code": "PR-113", "name": "routine blood draw", "class": "minor"},
                               {"code": "PR-114", "name": "day-case knee arthroscopy", "class": "surgical"},
                               {"code": "PR-115", "name": "dietary counselling", "class": "advisory"}],
           "consent_forms": [{"class": "minor", "form": "Form A (verbal consent recorded)"},
                             {"class": "surgical", "form": "Form C (written consent, two signatures)"},
                             {"class": "advisory", "form": "no consent form required"}],
           "patient": {"age": 34, "capacity": "has capacity"}},
 "field": {"id": "consent_form", "type": "choice",
           "question": "Which consent form is needed for episode EP-2291?",
           "options": [{"value": "Form A (verbal consent recorded)"},
                       {"value": "Form C (written consent, two signatures)"},
                       {"value": "no consent form required"},
                       {"value": "a court order is required"}]},
 "target": "Form C (written consent, two signatures)", "abstention_cause": None,
 "rationale": "PR-114 is a day-case knee arthroscopy, which is in the surgical class, and the surgical class takes Form C."},
{
 "key": "mh24", "domain": "education",
 "state": "Jae is entered for the qualification 'Applied Science Level 3'. That qualification is awarded by the "
          "Meridian Awarding Body. Meridian sets its Level 3 written papers in January and June, and its Level 2 "
          "papers in June only. Jae's centre only enters candidates for the nearest available sitting after their "
          "coursework is signed off. Jae's coursework was signed off in October 2026.",
 "field": {"id": "sitting", "type": "choice",
           "question": "Which sitting will Jae be entered for?",
           "options": [{"value": "January 2027"}, {"value": "June 2027"},
                       {"value": "January 2028"}, {"value": "no sitting is available"}]},
 "target": "January 2027", "abstention_cause": None,
 "rationale": "The qualification is Level 3 with Meridian, whose Level 3 papers run in January and June, so the nearest sitting after an October 2026 sign-off is January 2027."},
{
 "key": "mh25", "domain": "retail",
 "state": {"basket": {"id": "B-7781", "lines": [{"sku": "SK-12", "category": "footwear", "gbp": 90},
                                                {"sku": "SK-40", "category": "accessories", "gbp": 30}]},
           "promotions": [{"code": "FOOT20", "applies_to": "footwear", "discount": "20 percent", "min_spend_gbp": 80},
                          {"code": "ACC10", "applies_to": "accessories", "discount": "10 percent", "min_spend_gbp": 40},
                          {"code": "ALL5", "applies_to": "any category", "discount": "5 percent", "min_spend_gbp": 100}],
           "rules": ["A promotion's minimum spend is tested against the lines in its own category only.",
                     "Only one promotion may be applied to a basket.",
                     "Where more than one qualifies, the one giving the largest cash discount is applied."]},
 "field": {"id": "promotion", "type": "choice",
           "question": "Which promotion code should be applied to basket B-7781?",
           "options": [{"value": "FOOT20"}, {"value": "ACC10"}, {"value": "ALL5"},
                       {"value": "no promotion qualifies"}]},
 "target": "FOOT20", "abstention_cause": None,
 "rationale": "Footwear spend of 90 GBP clears FOOT20's 80 GBP minimum for an 18 GBP discount, accessories spend of 30 GBP fails ACC10's 40 GBP minimum, and ALL5's minimum is tested on 'any category' spend of 120 GBP but yields only 6 GBP."},
{
 "key": "mh26", "domain": "finance_ops",
 "state": {"applicant": {"id": "A-771", "sector_code": "SC-4", "years_trading": 7},
           "sector_codes": [{"code": "SC-3", "sector": "hospitality", "risk_class": "elevated"},
                            {"code": "SC-4", "sector": "professional services", "risk_class": "standard"},
                            {"code": "SC-5", "sector": "construction", "risk_class": "elevated"}],
           "limit_bands": [{"risk_class": "standard", "years_trading_min": 5, "band": 4},
                           {"risk_class": "standard", "years_trading_min": 2, "band": 3},
                           {"risk_class": "elevated", "years_trading_min": 5, "band": 2},
                           {"risk_class": "elevated", "years_trading_min": 2, "band": 1}],
           "note": "Use the highest band whose years_trading_min the applicant meets, within their risk class."},
 "field": {"id": "credit_band", "type": "ordinal",
           "question": "Which credit limit band does applicant A-771 fall into?",
           "levels": [{"value": 1, "description": "Band 1, the lowest limit."},
                      {"value": 2, "description": "Band 2."},
                      {"value": 3, "description": "Band 3."},
                      {"value": 4, "description": "Band 4, the highest limit."}]},
 "target": 4, "abstention_cause": None,
 "rationale": "Sector code SC-4 is professional services with a standard risk class, and at 7 years trading the applicant meets the 5-year minimum for band 4."},
{
 "key": "mh27", "domain": "logistics",
 "state": "Job J-5519 carries goods for the customer account 'Pentland Stores'. Pentland Stores holds a Platinum "
          "service agreement. Under the dispatch standard, Platinum accounts are worked at priority 3, Gold at "
          "priority 2 and Standard at priority 1. A job whose promised delivery slot has already been missed is "
          "raised one priority level, to a maximum of 4. Job J-5519's promised slot ended two hours ago and the "
          "vehicle has not yet loaded.",
 "field": {"id": "priority", "type": "ordinal",
           "question": "What dispatch priority should job J-5519 be worked at?",
           "levels": [{"value": 1, "description": "Priority 1, lowest."},
                      {"value": 2, "description": "Priority 2."},
                      {"value": 3, "description": "Priority 3."},
                      {"value": 4, "description": "Priority 4, highest."}]},
 "target": 4, "abstention_cause": None,
 "rationale": "Pentland Stores is Platinum, which starts at priority 3, and the missed delivery slot raises it one level to 4."},
{
 "key": "mh28", "domain": "hr",
 "state": {"case": {"id": "GR-220", "employee_job_code": "MKT-5"},
           "escalation_matrix": [{"job_family": "Operations", "tier": 2},
                                 {"job_family": "Finance", "tier": 3},
                                 {"job_family": "Engineering", "tier": 3}],
           "job_code_families": [{"code": "OPS-3", "family": "Operations"},
                                 {"code": "FIN-3", "family": "Finance"},
                                 {"code": "ENG-6", "family": "Engineering"}],
           "note": "A grievance is heard at the tier its employee's job family carries. The two tables above are "
                   "the only mapping available to the case handler."},
 "field": {"id": "hearing_tier", "type": "ordinal",
           "question": "At which tier should grievance GR-220 be heard?",
           "levels": [{"value": 1, "description": "Tier 1, line manager."},
                      {"value": 2, "description": "Tier 2, department head."},
                      {"value": 3, "description": "Tier 3, executive panel."}]},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "The tier follows from the job family of code MKT-5, and neither table in the state maps MKT-5 to a family, so the chain cannot be completed."},
{
 "key": "mh29", "domain": "software_incidents",
 "state": "The degraded endpoint is /v2/search. In the dependency map, /v2/search depends on the index-reader "
          "service, and index-reader depends on the object store. The object store is currently returning errors for "
          "12 percent of reads. The impact scale says: an endpoint is at impact 1 when a dependency two or more hops "
          "away is degraded, impact 2 when a direct dependency is degraded, and impact 3 when the endpoint itself is "
          "down. /v2/search is still serving every request, using stale results.",
 "field": {"id": "impact", "type": "ordinal",
           "question": "What impact level should be recorded for /v2/search?",
           "levels": [{"value": 1, "description": "Impact 1, an indirect dependency is degraded."},
                      {"value": 2, "description": "Impact 2, a direct dependency is degraded."},
                      {"value": 3, "description": "Impact 3, the endpoint itself is down."}]},
 "target": 1, "abstention_cause": None,
 "rationale": "The failing object store is two hops from /v2/search, which is itself still serving every request, so the scale puts it at impact 1."},
{
 "key": "mh30", "domain": "healthcare_admin",
 "state": {"patient": {"id": "P-8832", "ward_code": "W-12"},
           "wards": [{"code": "W-11", "speciality": "general medicine", "falls_baseline": 1},
                     {"code": "W-12", "speciality": "stroke rehabilitation", "falls_baseline": 2},
                     {"code": "W-13", "speciality": "day surgery", "falls_baseline": 1}],
           "modifiers": [{"factor": "prescribed a sedative in the last 24 hours", "add": 1},
                         {"factor": "fall recorded in the last 7 days", "add": 1}],
           "patient_factors": ["prescribed a sedative in the last 24 hours"],
           "note": "The falls risk score is the ward baseline plus every applicable modifier, capped at 4."},
 "field": {"id": "falls_risk", "type": "ordinal",
           "question": "What falls risk score should be recorded for patient P-8832?",
           "levels": [{"value": 1, "description": "Low falls risk."},
                      {"value": 2, "description": "Moderate falls risk."},
                      {"value": 3, "description": "High falls risk."},
                      {"value": 4, "description": "Very high falls risk."}]},
 "target": 3, "abstention_cause": None,
 "rationale": "Ward W-12 is stroke rehabilitation with a baseline of 2, and the one applicable modifier, a sedative in the last 24 hours, adds 1 for a score of 3."},
]
