"""temporal_numeric: dates, durations, counts and thresholds that need arithmetic or ordering."""

ITEMS = [
{
 "key": "tn01", "domain": "logistics",
 "state": {"shipment": "SH-4410", "departure_utc": "2026-03-18T22:15",
           "transit_hours": 41, "customs_clearance_hours": 0,
           "buyer_cutoff_utc": "2026-03-20T16:00", "mode": "road freight, single driver pair",
           "origin": "Zaragoza cross-dock", "destination": "Lyon regional distribution centre",
           "booking_reference": "BK-77120", "temperature_controlled": False,
           "note": "The shipment meets the cutoff if it arrives at or before the buyer's cutoff time. "
                   "Transit time already includes every planned break and the border crossing."},
 "field": {"id": "meets_cutoff", "type": "boolean",
           "question": "Does shipment SH-4410 arrive at or before the buyer's cutoff?"},
 "target": True, "abstention_cause": None,
 "rationale": "41 hours after 18 March 22:15 is 20 March 15:15 UTC, which is 45 minutes before the 16:00 cutoff."},
{
 "key": "tn02", "domain": "finance_ops",
 "state": "The account carries a monthly maintenance fee whenever the average daily balance for the statement month "
          "is below 1,500 USD. The statement month has 30 days. The closing balance was 1,800 USD on each of the "
          "first 10 days, 1,200 USD on each of the next 12 days, and 900 USD on each of the final 8 days. No other "
          "fees or waivers apply to this account, and the balance never changed within a day.",
 "field": {"id": "fee_applies", "type": "boolean",
           "question": "Does the maintenance fee apply for this statement month?"},
 "target": True, "abstention_cause": None,
 "rationale": "The average daily balance is (1,800x10 + 1,200x12 + 900x8) / 30 = 1,320 USD, which is below the 1,500 USD threshold."},
{
 "key": "tn03", "domain": "healthcare_admin",
 "state": {"patient": "P-2210", "medication": "analgesic X",
           "prescription": {"minimum_interval_hours": 6, "maximum_doses_per_24h": 4},
           "doses_given": ["06:00", "11:30", "17:00", "22:30"],
           "ward": "W-07", "administering_staff": ["RN Okafor", "RN Blythe", "RN Okafor", "RN Sandhu"],
           "date": "2026-04-22", "doses_refused_by_patient": 0, "dose_strength_mg": 500,
           "audit_question": "Were the prescribed spacing rules followed on this day?"},
 "field": {"id": "spacing_followed", "type": "boolean",
           "question": "Was every dose given at least the prescribed minimum interval after the previous one?"},
 "target": False, "abstention_cause": None,
 "rationale": "The three gaps are 5 hours 30 minutes each, short of the 6-hour minimum, even though the four doses stay inside the daily maximum."},
{
 "key": "tn04", "domain": "hr",
 "state": "Continuous service at Ledbury Foods is broken by any gap of more than 8 weeks between leaving and "
          "rejoining; a shorter gap is bridged and service is treated as continuous from the original start date. "
          "Samira started on 3 February 2024, left on 30 June 2025, and rejoined on 1 September 2025. She has worked "
          "there without interruption since rejoining, and no other break has ever been recorded.",
 "field": {"id": "continuous_from_2024", "type": "boolean",
           "question": "Is Samira's continuous service dated from 3 February 2024?"},
 "target": False, "abstention_cause": None,
 "rationale": "The gap from 30 June to 1 September 2025 is 63 days, longer than the 56 days that 8 weeks allows, so continuity is broken and service runs from the rejoining date."},
{
 "key": "tn05", "domain": "education",
 "state": {"student": "S-7781", "module": "LW220",
           "sessions_scheduled": 48, "sessions_attended": 37, "authorised_absences": 3,
           "term": "Spring 2026", "session_type": "seminar", "unauthorised_absences": 8,
           "previous_warning_issued": True, "exam_date": "2026-05-18",
           "rule": "Attendance is measured as sessions attended divided by sessions scheduled less authorised "
                   "absences. A student must reach 80 percent to be entered for the examination."},
 "field": {"id": "may_sit_exam", "type": "boolean",
           "question": "Does this student meet the attendance requirement to sit the LW220 examination?"},
 "target": True, "abstention_cause": None,
 "rationale": "Removing the 3 authorised absences leaves 45 countable sessions and 37 of 45 is 82.2 percent, above the 80 percent requirement."},
{
 "key": "tn06", "domain": "software_incidents",
 "state": "The contract promises 99.9 percent availability measured over a calendar month. The month in question had "
          "30 days. Two incidents took the service down: one lasting 31 minutes and one lasting 16 minutes. There "
          "were no other periods of unavailability, and scheduled maintenance did not occur that month. The "
          "contract measures availability on wall-clock minutes of full unavailability only; partial degradation is "
          "excluded, and the customer has not disputed either incident duration.",
 "field": {"id": "sla_met", "type": "boolean",
           "question": "Was the availability commitment met for that month?"},
 "target": False, "abstention_cause": None,
 "rationale": "99.9 percent of a 30-day month allows 43.2 minutes of downtime and the two incidents total 47 minutes."},
{
 "key": "tn07", "domain": "travel",
 "state": {"itinerary": "SK220 then SK911", "inbound_arrival_local": "14:35",
           "inbound_terminal": "T3", "outbound_departure_local": "16:05", "outbound_terminal": "T1",
           "airport_note": "The minimum connecting time at this airport depends on the terminal pair and is "
                           "published in a separate table that is not reproduced here.",
           "known_times": {"T3 to T3": "45 minutes", "T1 to T1": "40 minutes"}},
 "field": {"id": "legal_connection", "type": "boolean",
           "question": "Is the 90-minute connection from SK220 to SK911 a legal connection?"},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "The connection is 90 minutes, but the test is the minimum connecting time for the T3-to-T1 pair, which the state does not give and cannot be inferred from the two same-terminal figures."},
{
 "key": "tn08", "domain": "retail",
 "state": "The replenishment rule is: raise a purchase order when on-hand stock falls to the reorder point or below. "
          "The reorder point is average daily sales multiplied by supplier lead time in days, plus safety stock. For "
          "this line, average daily sales are 14 units, supplier lead time is 9 days and safety stock is 40 units. "
          "On-hand stock this morning is 168 units, with no purchase order already open and no stock in transit.",
 "field": {"id": "reorder_now", "type": "boolean",
           "question": "Should a purchase order be raised for this line this morning?"},
 "target": False, "abstention_cause": None,
 "rationale": "The reorder point is 14 x 9 + 40 = 166 units and on-hand stock of 168 is still above it."},
{
 "key": "tn09", "domain": "finance_ops",
 "state": {"invoice": "INV-2288", "invoice_date": "2026-01-31", "terms": "net 60 from the invoice date",
           "supplier": "Aldemar Components", "amount_eur": 9840.00, "currency": "EUR",
           "goods_received_date": "2026-02-04", "purchase_order": "PO-55021",
           "year_note": "2026 is not a leap year.",
           "weekend_rule": "The due date is not moved when it falls on a weekend or a public holiday.",
           "definition": "Net 60 means payment falls due 60 calendar days after the invoice date."},
 "field": {"id": "due_date", "type": "choice",
           "question": "On what date does INV-2288 fall due?",
           "options": [{"value": "2026-03-30"}, {"value": "2026-03-31"}, {"value": "2026-04-01"},
                       {"value": "2026-04-02"}, {"value": "2026-04-30"}]},
 "target": "2026-04-01", "abstention_cause": None,
 "rationale": "Counting 60 days from 31 January reaches 28 February at day 28, 31 March at day 59 and 1 April at day 60."},
{
 "key": "tn10", "domain": "logistics",
 "state": "The order is picked onto standard pallets. Each pallet holds up to 48 cartons, and cartons of different "
          "SKUs are never mixed on one pallet. The order is for three SKUs: 400 cartons of SKU A, 380 cartons of "
          "SKU B and 350 cartons of SKU C. Part-filled pallets are shipped as they are; no consolidation across "
          "SKUs is permitted.",
 "field": {"id": "pallet_count", "type": "choice",
           "question": "How many pallets does this order need?",
           "options": [{"value": "23"}, {"value": "24"}, {"value": "25"},
                       {"value": "26"}, {"value": "28"}]},
 "target": "25", "abstention_cause": None,
 "rationale": "SKU A needs 9 pallets, SKU B needs 8 and SKU C needs 8 once each is rounded up separately, giving 25."},
{
 "key": "tn11", "domain": "healthcare_admin",
 "state": {"clinic": "Dermatology, Room 4", "session_start": "09:00", "session_end": "12:30",
           "slot_minutes": 20, "administrative_block": {"from": "11:00", "to": "11:30"},
           "day": "Wednesday", "consultant": "Dr Whitlock", "room_capacity": 1,
           "overbooking_permitted": False, "emergency_slots_reserved": 0,
           "rule": "Slots run back to back from the session start, are never split across the administrative block, "
                   "and only whole slots are bookable."},
 "field": {"id": "slot_count", "type": "choice",
           "question": "How many bookable slots does this session hold?",
           "options": [{"value": "7"}, {"value": "8"}, {"value": "9"},
                       {"value": "10"}, {"value": "12"}]},
 "target": "9", "abstention_cause": None,
 "rationale": "The session is 210 minutes long, the administrative block removes 30, and the remaining 180 minutes divide exactly into nine 20-minute slots."},
{
 "key": "tn12", "domain": "hr",
 "state": {"employee": "E-4402", "standard_week_hours": 37.5, "hours_worked": 46,
           "base_rate_per_hour": 18.00,
           "overtime_rules": ["The first 4 overtime hours in a week are paid at 1.25 times the base rate.",
                              "Overtime beyond that is paid at 1.5 times the base rate."],
           "question_note": "Basic pay for the standard week is excluded from the figure asked for."},
 "field": {"id": "overtime_pay", "type": "choice",
           "question": "What is this week's overtime pay?",
           "options": [{"value": "153.00"}, {"value": "191.25"}, {"value": "211.50"},
                       {"value": "229.50"}, {"value": "247.50"}]},
 "target": "211.50", "abstention_cause": None,
 "rationale": "Overtime is 8.5 hours: 4 hours at 22.50 is 90.00 and 4.5 hours at 27.00 is 121.50, totalling 211.50."},
{
 "key": "tn13", "domain": "education",
 "state": {"student": "S-1190", "year": 2,
           "modules": [{"code": "BU201", "credits": 30, "mark": 62},
                       {"code": "BU202", "credits": 30, "mark": 55},
                       {"code": "BU210", "credits": 60, "mark": 71}],
           "programme": "BSc Business Management", "academic_year": "2025/26",
           "resits_taken": 0, "mitigating_circumstances": None,
           "rule": "The year mark is the credit-weighted average of the module marks, rounded to the nearest whole "
                   "mark, with halves rounded up. All three modules were passed at the first attempt."},
 "field": {"id": "year_mark", "type": "choice",
           "question": "What is this student's year mark?",
           "options": [{"value": "62"}, {"value": "63"}, {"value": "64"},
                       {"value": "65"}, {"value": "67"}]},
 "target": "65", "abstention_cause": None,
 "rationale": "The weighted total is 62x30 + 55x30 + 71x60 = 7,770 over 120 credits, which is 64.75 and rounds up to 65."},
{
 "key": "tn14", "domain": "travel",
 "state": {"leg_1": {"departs_local": "2026-02-11T15:50", "departure_utc_offset": "+04:00",
                     "flight_time": "6 hours 20 minutes", "arrival_airport_utc_offset": "+01:00"},
           "leg_2": {"departs_local": "2026-02-12T07:15", "departure_utc_offset": "+01:00"},
           "note": "Both legs use the same airport for the connection and neither date crosses a clock change."},
 "field": {"id": "layover", "type": "choice",
           "question": "How long is the layover between the two legs?",
           "options": [{"value": "11 hours 5 minutes"}, {"value": "12 hours 5 minutes"},
                       {"value": "12 hours 25 minutes"}, {"value": "13 hours 5 minutes"},
                       {"value": "15 hours 25 minutes"}]},
 "target": "12 hours 5 minutes", "abstention_cause": None,
 "rationale": "Departure at 15:50 UTC+4 is 11:50 UTC, arrival is 18:10 UTC or 19:10 local, and 19:10 to 07:15 the next morning is 12 hours 5 minutes."},
{
 "key": "tn15", "domain": "finance_ops",
 "state": "The invoice is for a net amount of 2,480.00 before tax. The customer is offered a 2 percent early "
          "settlement discount for payment within 10 days of the invoice date. Under the agreed treatment, the tax "
          "is charged at 20 percent on the discounted net amount, not on the full net amount. The customer paid on "
          "day 7 and no other adjustments apply to this invoice.",
 "field": {"id": "amount_paid", "type": "choice",
           "question": "What total did the customer pay?",
           "options": [{"value": "2,430.40"}, {"value": "2,916.48"}, {"value": "2,918.40"},
                       {"value": "2,921.60"}, {"value": "2,976.00"}]},
 "target": "2,916.48", "abstention_cause": None,
 "rationale": "The discounted net is 2,480.00 x 0.98 = 2,430.40 and adding 20 percent tax gives 2,916.48."},
{
 "key": "tn16", "domain": "software_incidents",
 "state": {"slo": "99.5 percent of requests succeed, measured over a 28-day window",
           "window_requests": 4200000, "window_errors": 18500, "days_elapsed_in_window": 19,
           "service": "checkout-api", "environment": "production", "burn_alerts_fired": 2,
           "largest_single_incident_errors": 7100, "deploy_freeze_active": False,
           "note": "The error budget is the number of failed requests the SLO permits over the whole window, "
                   "counted against the total request volume for that window."},
 "field": {"id": "budget_used", "type": "choice",
           "question": "Roughly how much of the error budget has been consumed?",
           "options": [{"value": "about 44 percent"}, {"value": "about 66 percent"},
                       {"value": "about 88 percent"}, {"value": "about 110 percent"},
                       {"value": "the budget is already exhausted"}]},
 "target": "about 88 percent", "abstention_cause": None,
 "rationale": "The budget is 0.5 percent of 4,200,000 requests, or 21,000 errors, and 18,500 of those is about 88 percent."},
{
 "key": "tn17", "domain": "retail",
 "state": {"line": "SKU-6621 waterproof jacket", "unit_cost": 27.40, "current_price": 44.99,
           "season": "Autumn/Winter 2026", "units_on_hand": 340, "weeks_on_sale": 11,
           "competitor_price": 39.99, "supplier_rebate": 0.00,
           "markdown_rule": "A markdown may not take the gross margin below 25 percent of the selling price. "
                            "Gross margin is the selling price less the unit cost, divided by the selling price.",
           "rounding": "Prices are quoted to the penny, and a price is only permitted if it satisfies the rule."},
 "field": {"id": "lowest_price", "type": "choice",
           "question": "What is the lowest markdown price permitted for this line?",
           "options": [{"value": "33.75"}, {"value": "34.25"}, {"value": "36.53"},
                       {"value": "36.54"}, {"value": "36.99"}]},
 "target": "36.54", "abstention_cause": None,
 "rationale": "The margin rule requires a price of at least 27.40 / 0.75 = 36.5333, and at 36.53 the margin is 24.99 percent, so the lowest permitted price to the penny is 36.54."},
{
 "key": "tn18", "domain": "logistics",
 "state": "A driver may spend at most 9 hours driving in a day, which may be extended to 10 hours on no more than "
          "two days in a week. This driver has already used both extended days this week. So far today he has driven "
          "7 hours 20 minutes. Two legs remain on his schedule, each with 55 minutes of driving. Breaks do not count "
          "as driving time and do not raise the daily driving limit.",
 "field": {"id": "legs_allowed", "type": "choice",
           "question": "How many of the two remaining legs may this driver drive today?",
           "options": [{"value": "neither leg"}, {"value": "one leg"}, {"value": "both legs"},
                       {"value": "both legs, if he takes a 45-minute break first"}]},
 "target": "one leg", "abstention_cause": None,
 "rationale": "One more leg takes him to 8 hours 15 minutes, inside the 9-hour limit, while both would reach 9 hours 10 minutes, and the extensions for the week are used up."},
{
 "key": "tn19", "domain": "healthcare_admin",
 "state": {"patient": "P-5514", "age": 72, "sex": "female", "serum_creatinine_umol_l": 118,
           "weight_kg": None,
           "dosing_table": [{"creatinine_clearance": "above 50 mL/min", "band": "full dose"},
                            {"creatinine_clearance": "30 to 50 mL/min", "band": "reduced dose"},
                            {"creatinine_clearance": "below 30 mL/min", "band": "contraindicated"}],
           "note": "Creatinine clearance is calculated from age, sex, serum creatinine and body weight."},
 "field": {"id": "dose_band", "type": "choice",
           "question": "Which dosing band applies to this patient?",
           "options": [{"value": "full dose"}, {"value": "reduced dose"},
                       {"value": "contraindicated"}, {"value": "seek a specialist opinion"}]},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "The band follows from creatinine clearance, whose calculation needs body weight, and no weight is recorded for this patient."},
{
 "key": "tn20", "domain": "education",
 "state": "Results were published on Friday 12 June 2026. An appeal must be filed within 10 working days. The clock "
          "starts on the first working day after publication. Saturdays and Sundays are not working days, and the "
          "university was closed for a local holiday on Monday 15 June 2026, which is not counted as a working day. "
          "No other closures fall in that period.",
 "field": {"id": "appeal_deadline", "type": "choice",
           "question": "What is the last day on which an appeal may be filed?",
           "options": [{"value": "Friday 26 June 2026"}, {"value": "Monday 29 June 2026"},
                       {"value": "Tuesday 30 June 2026"}, {"value": "Wednesday 1 July 2026"},
                       {"value": "Friday 3 July 2026"}]},
 "target": "Monday 29 June 2026", "abstention_cause": None,
 "rationale": "Counting Tuesday 16 June as day 1 and skipping weekends and the 15 June closure, the tenth working day is Monday 29 June."},
{
 "key": "tn21", "domain": "finance_ops",
 "state": {"invoice": "INV-7714", "due_date": "2026-05-04", "today": "2026-07-01",
           "paid": False, "customer": "Halberd Retail Group", "amount_gbp": 18240.00,
           "credit_notes_applied": 0, "on_payment_plan": False, "disputed": False,
           "last_contact": "2026-06-18", "collections_owner": "M. Ferreira",
           "aging_buckets": ["1: 1 to 30 days overdue", "2: 31 to 60 days overdue",
                             "3: 61 to 90 days overdue", "4: more than 90 days overdue"]},
 "field": {"id": "aging_bucket", "type": "ordinal",
           "question": "Which aging bucket does INV-7714 sit in today?",
           "levels": [{"value": 1, "description": "1 to 30 days overdue."},
                      {"value": 2, "description": "31 to 60 days overdue."},
                      {"value": 3, "description": "61 to 90 days overdue."},
                      {"value": 4, "description": "More than 90 days overdue."}]},
 "target": 2, "abstention_cause": None,
 "rationale": "From 4 May to 1 July is 58 days overdue, which falls in the 31-to-60-day bucket."},
{
 "key": "tn22", "domain": "logistics",
 "state": "The service was scheduled to arrive at 06:30 and actually arrived at 09:05 the same morning. The customer "
          "scorecard records a delay band for every arrival: band 1 for a delay under 30 minutes, band 2 for 30 "
          "minutes up to 2 hours, band 3 for 2 hours up to 4 hours, and band 4 for 4 hours or more. There was no "
          "change to the scheduled time and the arrival was recorded automatically at the gate.",
 "field": {"id": "delay_band", "type": "ordinal",
           "question": "Which delay band should the scorecard record?",
           "levels": [{"value": 1, "description": "Band 1, under 30 minutes late."},
                      {"value": 2, "description": "Band 2, 30 minutes to under 2 hours late."},
                      {"value": 3, "description": "Band 3, 2 hours to under 4 hours late."},
                      {"value": 4, "description": "Band 4, 4 hours or more late."}]},
 "target": 3, "abstention_cause": None,
 "rationale": "06:30 to 09:05 is 155 minutes, which is 2 hours 35 minutes and falls in band 3."},
{
 "key": "tn23", "domain": "healthcare_admin",
 "state": {"pathway": "elective orthopaedics", "referral_received": "2026-01-08",
           "treatment_date": "2026-06-02", "clock_stops": [],
           "bands": ["1: up to 6 weeks", "2: 7 to 12 weeks", "3: 13 to 18 weeks", "4: more than 18 weeks"],
           "note": "The waiting time is measured in whole weeks from referral to treatment, with no clock stops."},
 "field": {"id": "wait_band", "type": "ordinal",
           "question": "Which waiting-time band does this pathway fall into?",
           "levels": [{"value": 1, "description": "Up to 6 weeks."},
                      {"value": 2, "description": "7 to 12 weeks."},
                      {"value": 3, "description": "13 to 18 weeks."},
                      {"value": 4, "description": "More than 18 weeks."}]},
 "target": 4, "abstention_cause": None,
 "rationale": "8 January to 2 June is 145 days, which is 20 whole weeks and beyond the 18-week boundary."},
{
 "key": "tn24", "domain": "hr",
 "state": {"employee": "E-9912", "start_date": "2022-07-05", "reference_date": "2026-04-01",
           "breaks_in_service": [], "contract": "permanent, full time", "grade": 3,
           "location": "Cardiff office", "purchased_days": 0, "carried_days": 2,
           "note": "Only completed years of continuous service count toward the tier.",
           "entitlement_tiers": ["1: under 2 completed years, 25 days",
                                 "2: 2 to 4 completed years, 27 days",
                                 "3: 5 to 9 completed years, 30 days",
                                 "4: 10 or more completed years, 33 days"]},
 "field": {"id": "entitlement_tier", "type": "ordinal",
           "question": "Which leave entitlement tier does this employee hold on the reference date?",
           "levels": [{"value": 1, "description": "Tier 1, 25 days."},
                      {"value": 2, "description": "Tier 2, 27 days."},
                      {"value": 3, "description": "Tier 3, 30 days."},
                      {"value": 4, "description": "Tier 4, 33 days."}]},
 "target": 2, "abstention_cause": None,
 "rationale": "By 1 April 2026 the employee has completed 3 years of service, since the fourth anniversary falls on 5 July 2026, placing them in the 2-to-4-year tier."},
{
 "key": "tn25", "domain": "education",
 "state": "The final classification uses the unweighted mean of four equally weighted module marks, rounded to two "
          "decimal places and then classified. The marks are 58, 64, 61 and 70. The classification bands are: below "
          "40 is a fail, 40 to 49 is third class, 50 to 59 is lower second, 60 to 69 is upper second, and 70 or "
          "above is first class. No discretionary uplift has been applied by the board.",
 "field": {"id": "classification", "type": "ordinal",
           "question": "Which classification band does this student fall into?",
           "levels": [{"value": 1, "description": "Fail, below 40."},
                      {"value": 2, "description": "Third class, 40 to 49."},
                      {"value": 3, "description": "Lower second, 50 to 59."},
                      {"value": 4, "description": "Upper second, 60 to 69."},
                      {"value": 5, "description": "First class, 70 or above."}]},
 "target": 4, "abstention_cause": None,
 "rationale": "The four marks sum to 253 and the mean is 63.25, which sits in the 60-to-69 upper second band."},
{
 "key": "tn26", "domain": "software_incidents",
 "state": {"window": "the last 15 minutes", "requests": 240000, "errors": 180,
           "severity_scale": ["1: error rate under 0.1 percent",
                              "2: error rate 0.1 up to 0.5 percent",
                              "3: error rate 0.5 up to 2 percent",
                              "4: error rate 2 percent or above"],
           "note": "Severity is set from the error rate over the window and from nothing else."},
 "field": {"id": "severity_level", "type": "ordinal",
           "question": "Which severity level does the current error rate indicate?",
           "levels": [{"value": 1, "description": "Level 1, error rate under 0.1 percent."},
                      {"value": 2, "description": "Level 2, error rate 0.1 up to 0.5 percent."},
                      {"value": 3, "description": "Level 3, error rate 0.5 up to 2 percent."},
                      {"value": 4, "description": "Level 4, error rate 2 percent or above."}]},
 "target": 1, "abstention_cause": None,
 "rationale": "180 errors in 240,000 requests is 0.075 percent, below the 0.1 percent boundary for level 1."},
{
 "key": "tn27", "domain": "retail",
 "state": "Weeks of cover is on-hand stock divided by average weekly sales. This line has 465 units on hand and "
          "average weekly sales of 155 units. The buying team reads the result against four bands: under 4 weeks is "
          "band 1 and triggers an immediate order, 4 to under 8 weeks is band 2, 8 to 12 weeks is band 3, and more "
          "than 12 weeks is band 4 and flags overstock. There is nothing on order and nothing in transit.",
 "field": {"id": "cover_band", "type": "ordinal",
           "question": "Which weeks-of-cover band does this line fall into?",
           "levels": [{"value": 1, "description": "Band 1, under 4 weeks of cover."},
                      {"value": 2, "description": "Band 2, 4 to under 8 weeks."},
                      {"value": 3, "description": "Band 3, 8 to 12 weeks."},
                      {"value": 4, "description": "Band 4, more than 12 weeks, overstocked."}]},
 "target": 1, "abstention_cause": None,
 "rationale": "465 divided by 155 is exactly 3 weeks of cover, which is under the 4-week boundary for band 1."},
{
 "key": "tn28", "domain": "travel",
 "state": {"service": "coach route 88", "scheduled_arrival": "2026-09-03T21:50",
           "actual_arrival": "2026-09-04T01:35",
           "tiers": ["1: under 60 minutes late, no payment",
                     "2: 60 to under 180 minutes late, refreshments",
                     "3: 180 to under 300 minutes late, refreshments and a 50 percent refund",
                     "4: 300 minutes or more late, full refund and overnight accommodation"],
           "cause": "mechanical failure within the operator's control"},
 "field": {"id": "care_tier", "type": "ordinal",
           "question": "Which passenger care tier applies to this arrival?",
           "levels": [{"value": 1, "description": "Tier 1, no payment."},
                      {"value": 2, "description": "Tier 2, refreshments."},
                      {"value": 3, "description": "Tier 3, refreshments and a 50 percent refund."},
                      {"value": 4, "description": "Tier 4, full refund and overnight accommodation."}]},
 "target": 3, "abstention_cause": None,
 "rationale": "21:50 to 01:35 the following day is 225 minutes, which falls in the 180-to-299-minute tier."},
{
 "key": "tn29", "domain": "finance_ops",
 "state": "The loan agreement caps net leverage, defined as net debt divided by EBITDA, at 3.5 times. At the test "
          "date net debt is 12.6 million and EBITDA for the trailing twelve months is 4.2 million. The treasury "
          "dashboard reports headroom in four bands: band 1 where the covenant is breached, band 2 where headroom is "
          "0.25 times or less, band 3 where headroom is more than 0.25 and up to 0.75 times, and band 4 where "
          "headroom is more than 0.75 times.",
 "field": {"id": "headroom_band", "type": "ordinal",
           "question": "Which covenant headroom band should the dashboard show at this test date?",
           "levels": [{"value": 1, "description": "Band 1, covenant breached."},
                      {"value": 2, "description": "Band 2, headroom of 0.25 times or less."},
                      {"value": 3, "description": "Band 3, headroom above 0.25 and up to 0.75 times."},
                      {"value": 4, "description": "Band 4, headroom above 0.75 times."}]},
 "target": 3, "abstention_cause": None,
 "rationale": "12.6 divided by 4.2 is 3.0 times, leaving 0.5 times of headroom against the 3.5 times cap, which is band 3."},
{
 "key": "tn30", "domain": "logistics",
 "state": {"trailer": "TR-2201", "pallet_spaces": 33, "pallets_loaded": 31,
           "route": "Bristol to Carlisle trunk", "departure": "2026-10-07T20:15",
           "gross_weight_kg": 18400, "weight_limit_kg": 26000, "double_stacked": False,
           "utilisation_bands": ["1: under 50 percent", "2: 50 to under 75 percent",
                                 "3: 75 to under 90 percent", "4: 90 percent or above"],
           "note": "Utilisation is pallets loaded divided by pallet spaces; weight is not a constraint on this load."},
 "field": {"id": "utilisation_band", "type": "ordinal",
           "question": "Which utilisation band does this trailer load fall into?",
           "levels": [{"value": 1, "description": "Band 1, under 50 percent."},
                      {"value": 2, "description": "Band 2, 50 to under 75 percent."},
                      {"value": 3, "description": "Band 3, 75 to under 90 percent."},
                      {"value": 4, "description": "Band 4, 90 percent or above."}]},
 "target": 4, "abstention_cause": None,
 "rationale": "31 pallets in 33 spaces is 93.9 percent, at or above the 90 percent boundary for band 4."},
]
