"""tradeoff: pick the option that best satisfies the stated weighted priorities.

Structured items carry `priorities` (criterion -> integer weight) and `options`
(name -> criterion -> rating on the stated scale); the answer is the highest weighted
total. Prose items state the same trade-off in words.
"""

ITEMS = [
{
 "key": "td01", "domain": "finance_ops",
 "state": {"decision": "choose a payments processor for the new storefront",
           "scale": "each option is rated 1 (poor) to 5 (excellent) on each criterion",
           "priorities": {"settlement speed": 5, "fee level": 3, "integration effort": 2},
           "options": {"Vendor A": {"settlement speed": 5, "fee level": 2, "integration effort": 4},
                       "Vendor B": {"settlement speed": 3, "fee level": 5, "integration effort": 3}},
           "rule": "Choose the option with the highest weighted total; the weights above are fixed and no other "
                   "factor is in scope."},
 "field": {"id": "pick_vendor_a", "type": "boolean",
           "question": "Do the stated priorities favour Vendor A over Vendor B?"},
 "target": True, "abstention_cause": None,
 "rationale": "Vendor A scores 25 + 6 + 8 = 39 against Vendor B's 15 + 15 + 6 = 36, so the weighted priorities favour Vendor A."},
{
 "key": "td02", "domain": "hr",
 "state": "The team is choosing a working pattern for next year. The priorities are, with their weights: coverage of "
          "the customer phone line between 08:00 and 18:00 (weight 5), predictable hours for staff with caring "
          "responsibilities (weight 3), and reducing commuting cost (weight 2). Rated 1 to 5 on each: the "
          "compressed four-day week scores 2 on coverage, 3 on predictability and 5 on commuting cost. The "
          "staggered five-day week scores 5 on coverage, 4 on predictability and 2 on commuting cost. The rule is "
          "to take the highest weighted total.",
 "field": {"id": "compressed_wins", "type": "boolean",
           "question": "Is the compressed four-day week the pattern that best satisfies the stated priorities?"},
 "target": False, "abstention_cause": None,
 "rationale": "The compressed week totals 10 + 9 + 10 = 29 while the staggered week totals 25 + 12 + 4 = 41, so the staggered pattern wins."},
{
 "key": "td03", "domain": "logistics",
 "state": {"decision": "choose a carrier for the weekly trunk run",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"on-time reliability": 5, "cost per trip": 4, "capacity flexibility": 2,
                          "emissions": 1},
           "options": {"Ostler Freight": {"on-time reliability": 5, "cost per trip": 2, "capacity flexibility": 3, "emissions": 2},
                       "Brindle Haulage": {"on-time reliability": 4, "cost per trip": 4, "capacity flexibility": 2, "emissions": 3},
                       "Caldy Transport": {"on-time reliability": 3, "cost per trip": 5, "capacity flexibility": 5, "emissions": 4}},
           "rule": "Take the highest weighted total. Ties would be broken on reliability, but no tie is expected."},
 "field": {"id": "carrier", "type": "choice",
           "question": "Which carrier best satisfies the stated priorities?",
           "options": [{"value": "Ostler Freight"}, {"value": "Brindle Haulage"},
                       {"value": "Caldy Transport"}]},
 "target": "Caldy Transport", "abstention_cause": None,
 "rationale": "Weighted totals are Ostler 25 + 8 + 6 + 2 = 41, Brindle 20 + 16 + 4 + 3 = 43 and Caldy 15 + 20 + 10 + 4 = 49, so the cost and flexibility weights carry Caldy."},
{
 "key": "td04", "domain": "software_incidents",
 "state": {"decision": "choose the mitigation for a failing dependency during an incident",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"restores customer traffic fastest": 5, "risk of making things worse": 4,
                          "effort during the incident": 2},
           "options": {"fail over to the secondary region": {"restores customer traffic fastest": 5, "risk of making things worse": 2, "effort during the incident": 2},
                       "serve cached responses": {"restores customer traffic fastest": 4, "risk of making things worse": 5, "effort during the incident": 4},
                       "roll back the last release": {"restores customer traffic fastest": 2, "risk of making things worse": 4, "effort during the incident": 3},
                       "wait for the provider to recover": {"restores customer traffic fastest": 1, "risk of making things worse": 5, "effort during the incident": 5}},
           "note": "On 'risk of making things worse', 5 means the lowest risk."},
 "field": {"id": "mitigation", "type": "choice",
           "question": "Which mitigation best satisfies the stated priorities?",
           "options": [{"value": "fail over to the secondary region"}, {"value": "serve cached responses"},
                       {"value": "roll back the last release"}, {"value": "wait for the provider to recover"}]},
 "target": "serve cached responses", "abstention_cause": None,
 "rationale": "Serving cached responses totals 20 + 20 + 8 = 48, ahead of failover at 25 + 8 + 4 = 37, rollback at 10 + 16 + 6 = 32 and waiting at 5 + 20 + 10 = 35."},
{
 "key": "td05", "domain": "healthcare_admin",
 "state": {"decision": "choose how to cover a clinic session after a consultant calls in sick",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"patients seen on the day": 5, "clinical appropriateness": 5,
                          "cost to the department": 2, "staff goodwill": 1},
           "options": {"cancel and rebook the session": {"patients seen on the day": 1, "clinical appropriateness": 5, "cost to the department": 5, "staff goodwill": 4},
                       "book a locum consultant": {"patients seen on the day": 5, "clinical appropriateness": 5, "cost to the department": 1, "staff goodwill": 3},
                       "ask a registrar to run it unsupervised": {"patients seen on the day": 5, "clinical appropriateness": 2, "cost to the department": 4, "staff goodwill": 2},
                       "split patients across two later clinics": {"patients seen on the day": 2, "clinical appropriateness": 4, "cost to the department": 4, "staff goodwill": 2}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "cover_option", "type": "choice",
           "question": "Which cover option best satisfies the stated priorities?",
           "options": [{"value": "cancel and rebook the session"}, {"value": "book a locum consultant"},
                       {"value": "ask a registrar to run it unsupervised"},
                       {"value": "split patients across two later clinics"}]},
 "target": "book a locum consultant", "abstention_cause": None,
 "rationale": "The locum totals 25 + 25 + 2 + 3 = 55, ahead of the registrar at 25 + 10 + 8 + 2 = 45, cancellation at 5 + 25 + 10 + 4 = 44 and splitting at 10 + 20 + 8 + 2 = 40."},
{
 "key": "td06", "domain": "retail",
 "state": "The buying team must choose one supplier for the own-brand kettle. The stated priorities and weights are: "
          "landed unit cost (weight 5), lead time (weight 4), quality failure rate (weight 4) and minimum order "
          "quantity (weight 1). Each supplier is rated 1 to 5, where 5 is best. Supplier Kestrel: cost 5, lead time "
          "2, quality 3, minimum order 2. Supplier Larkmead: cost 3, lead time 4, quality 5, minimum order 4. "
          "Supplier Mendip: cost 4, lead time 5, quality 2, minimum order 5. The buyer takes the highest weighted "
          "total and nothing else is in scope.",
 "field": {"id": "supplier", "type": "choice",
           "question": "Which supplier best satisfies the stated priorities?",
           "options": [{"value": "Kestrel"}, {"value": "Larkmead"}, {"value": "Mendip"}]},
 "target": "Larkmead", "abstention_cause": None,
 "rationale": "Kestrel totals 25 + 8 + 12 + 2 = 47, Larkmead 15 + 16 + 20 + 4 = 55 and Mendip 20 + 20 + 8 + 5 = 53."},
{
 "key": "td07", "domain": "education",
 "state": {"decision": "choose a timetable pattern for the new foundation year",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"student contact hours": 4, "room utilisation": 3, "staff travel between sites": 2,
                          "compatibility with part-time students": 5},
           "options": {"two long days": {"student contact hours": 4, "room utilisation": 4, "staff travel between sites": 5, "compatibility with part-time students": 5},
                       "four short days": {"student contact hours": 5, "room utilisation": 3, "staff travel between sites": 2, "compatibility with part-time students": 2},
                       "three medium days": {"student contact hours": 5, "room utilisation": 5, "staff travel between sites": 3, "compatibility with part-time students": 3}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "pattern", "type": "choice",
           "question": "Which timetable pattern best satisfies the stated priorities?",
           "options": [{"value": "two long days"}, {"value": "four short days"},
                       {"value": "three medium days"}]},
 "target": "two long days", "abstention_cause": None,
 "rationale": "Two long days total 16 + 12 + 10 + 25 = 63, ahead of three medium days at 20 + 15 + 6 + 15 = 56 and four short days at 20 + 9 + 4 + 10 = 43."},
{
 "key": "td08", "domain": "travel",
 "state": "A business traveller must choose one itinerary. The traveller's stated priorities, with weights, are: "
          "arriving before the 09:00 meeting with time to spare (weight 5), total cost (weight 3), and avoiding an "
          "overnight departure (weight 3). Rated 1 to 5 where 5 is best: the 06:10 direct flight scores 5 on "
          "arrival, 2 on cost and 3 on avoiding an overnight; the 22:40 red-eye scores 4 on arrival, 5 on cost and "
          "1 on avoiding an overnight; the previous-evening flight with a hotel scores 5 on arrival, 1 on cost and "
          "5 on avoiding an overnight. The highest weighted total wins.",
 "field": {"id": "itinerary", "type": "choice",
           "question": "Which itinerary best satisfies the traveller's stated priorities?",
           "options": [{"value": "the 06:10 direct flight"}, {"value": "the 22:40 red-eye"},
                       {"value": "the previous-evening flight with a hotel"}]},
 "target": "the previous-evening flight with a hotel", "abstention_cause": None,
 "rationale": "The previous-evening option totals 25 + 3 + 15 = 43, ahead of the 06:10 flight at 25 + 6 + 9 = 40 and the red-eye at 20 + 15 + 3 = 38."},
{
 "key": "td09", "domain": "finance_ops",
 "state": {"decision": "choose where to place a 3 million cash surplus for 90 days",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"capital preservation": 5, "access within 5 business days": 4, "yield": 2},
           "options": {"overnight deposit": {"capital preservation": 5, "access within 5 business days": 5, "yield": 1},
                       "90-day term deposit": {"capital preservation": 5, "access within 5 business days": 1, "yield": 3},
                       "money market fund": {"capital preservation": 4, "access within 5 business days": 5, "yield": 3},
                       "short-dated corporate bond fund": {"capital preservation": 2, "access within 5 business days": 4, "yield": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "placement", "type": "choice",
           "question": "Where should the surplus be placed given the stated priorities?",
           "options": [{"value": "overnight deposit"}, {"value": "90-day term deposit"},
                       {"value": "money market fund"}, {"value": "short-dated corporate bond fund"}]},
 "target": "overnight deposit", "abstention_cause": None,
 "rationale": "The overnight deposit totals 25 + 20 + 2 = 47, just ahead of the money market fund at 20 + 20 + 6 = 46, with the term deposit at 35 and the bond fund at 36."},
{
 "key": "td10", "domain": "software_incidents",
 "state": {"decision": "choose the first engineering investment for next quarter",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"reduces repeat incidents": 5, "delivers within the quarter": 3,
                          "unblocks the roadmap": 3, "team enthusiasm": 1},
           "options": {"replace the queue library": {"reduces repeat incidents": 5, "delivers within the quarter": 2, "unblocks the roadmap": 4, "team enthusiasm": 4},
                       "add end-to-end tracing": {"reduces repeat incidents": 4, "delivers within the quarter": 4, "unblocks the roadmap": 3, "team enthusiasm": 3},
                       "rewrite the deploy pipeline": {"reduces repeat incidents": 3, "delivers within the quarter": 3, "unblocks the roadmap": 5, "team enthusiasm": 5},
                       "harden the retry logic": {"reduces repeat incidents": 5, "delivers within the quarter": 5, "unblocks the roadmap": 1, "team enthusiasm": 2}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "investment", "type": "choice",
           "question": "Which investment best satisfies the stated priorities?",
           "options": [{"value": "replace the queue library"}, {"value": "add end-to-end tracing"},
                       {"value": "rewrite the deploy pipeline"}, {"value": "harden the retry logic"}]},
 "target": "replace the queue library", "abstention_cause": None,
 "rationale": "Replacing the queue library totals 25 + 6 + 12 + 4 = 47, ahead of the retry work at 45, tracing at 44 and the pipeline rewrite at 44."},
{
 "key": "td11", "domain": "logistics",
 "state": "The depot must choose one way to clear a backlog before the weekend. The priorities and weights are: "
          "clearing every outstanding order (weight 5), keeping overtime spend down (weight 3), and avoiding damage "
          "risk from rushed handling (weight 4). Rated 1 to 5 where 5 is best: a Saturday overtime shift scores 5, "
          "3 and 4; hiring an agency crew scores 4, 3 and 2; pushing a third of the orders to Monday scores 2, 5 "
          "and 5; and running two extra evening hours all week scores 4, 2 and 4. The highest weighted total wins.",
 "field": {"id": "plan", "type": "choice",
           "question": "Which plan best satisfies the stated priorities?",
           "options": [{"value": "a Saturday overtime shift"}, {"value": "hiring an agency crew"},
                       {"value": "pushing a third of the orders to Monday"},
                       {"value": "two extra evening hours all week"}]},
 "target": "a Saturday overtime shift", "abstention_cause": None,
 "rationale": "The Saturday shift totals 25 + 9 + 16 = 50, ahead of the Monday deferral at 10 + 15 + 20 = 45, evening hours at 42 and the agency crew at 37."},
{
 "key": "td12", "domain": "hr",
 "state": {"decision": "choose a recruitment channel for a hard-to-fill role",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"quality of shortlist": 5, "time to hire": 4, "cost per hire": 2,
                          "diversity of applicants": 4},
           "options": {"specialist agency": {"quality of shortlist": 5, "time to hire": 5, "cost per hire": 1, "diversity of applicants": 2},
                       "internal referral scheme": {"quality of shortlist": 4, "time to hire": 4, "cost per hire": 5, "diversity of applicants": 1},
                       "targeted job boards": {"quality of shortlist": 3, "time to hire": 2, "cost per hire": 4, "diversity of applicants": 5},
                       "university partnership": {"quality of shortlist": 2, "time to hire": 1, "cost per hire": 4, "diversity of applicants": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "channel", "type": "choice",
           "question": "Which recruitment channel best satisfies the stated priorities?",
           "options": [{"value": "specialist agency"}, {"value": "internal referral scheme"},
                       {"value": "targeted job boards"}, {"value": "university partnership"}]},
 "target": "specialist agency", "abstention_cause": None,
 "rationale": "The agency totals 25 + 20 + 2 + 8 = 55, ahead of referrals at 50, job boards at 15 + 8 + 8 + 20 = 51 and the university partnership at 42."},
{
 "key": "td13", "domain": "retail",
 "state": {"decision": "choose the layout for the refitted store entrance",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"sales of promoted lines": 4, "queue flow at the tills": 5,
                          "accessibility for wheelchair users": 5, "fit cost": 1},
           "options": {"central promotional island": {"sales of promoted lines": 5, "queue flow at the tills": 2, "accessibility for wheelchair users": 2, "fit cost": 4},
                       "wide perimeter aisle": {"sales of promoted lines": 3, "queue flow at the tills": 4, "accessibility for wheelchair users": 5, "fit cost": 3},
                       "twin entry lanes": {"sales of promoted lines": 2, "queue flow at the tills": 5, "accessibility for wheelchair users": 4, "fit cost": 2}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "layout", "type": "choice",
           "question": "Which layout best satisfies the stated priorities?",
           "options": [{"value": "central promotional island"}, {"value": "wide perimeter aisle"},
                       {"value": "twin entry lanes"}]},
 "target": "wide perimeter aisle", "abstention_cause": None,
 "rationale": "The perimeter aisle totals 12 + 20 + 25 + 3 = 60, ahead of twin lanes at 8 + 25 + 20 + 2 = 55 and the island at 20 + 10 + 10 + 4 = 44."},
{
 "key": "td14", "domain": "healthcare_admin",
 "state": {"decision": "choose a supplier for the ward's infusion pumps",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"clinical safety record": 5, "training burden": 3, "total cost over 5 years": 4},
           "options": {"Supplier P": {"clinical safety record": 5, "training burden": 2, "total cost over 5 years": 2},
                       "Supplier Q": {"clinical safety record": 4, "training burden": 4, "total cost over 5 years": None},
                       "Supplier R": {"clinical safety record": 4, "training burden": 3, "total cost over 5 years": 4}},
           "note": "Supplier Q has not returned a five-year cost model, so its cost rating is not available; the "
                   "rule requires every criterion to be scored before a total is taken."},
 "field": {"id": "supplier", "type": "choice",
           "question": "Which supplier best satisfies the stated priorities?",
           "options": [{"value": "Supplier P"}, {"value": "Supplier Q"}, {"value": "Supplier R"}]},
 "target": None, "abstention_cause": "insufficient_evidence",
 "rationale": "Supplier Q has no cost rating and the weighted total cannot be formed, so the comparison cannot be completed as the rule requires."},
{
 "key": "td15", "domain": "education",
 "state": "The faculty must pick one way to spend a fixed widening-participation budget. The priorities and weights "
          "are: number of students reached (weight 3), effect on continuation rates (weight 5), and staff time "
          "required (weight 2, where 5 means least time). Rated 1 to 5: a bursary top-up scores 4, 4 and 5; a "
          "peer-mentoring scheme scores 3, 5 and 2; a summer bridging course scores 2, 5 and 1; and an outreach "
          "roadshow scores 5, 2 and 3. The faculty takes the highest weighted total.",
 "field": {"id": "programme", "type": "choice",
           "question": "Which programme best satisfies the stated priorities?",
           "options": [{"value": "a bursary top-up"}, {"value": "a peer-mentoring scheme"},
                       {"value": "a summer bridging course"}, {"value": "an outreach roadshow"}]},
 "target": "a bursary top-up", "abstention_cause": None,
 "rationale": "The bursary totals 12 + 20 + 10 = 42, ahead of peer mentoring at 9 + 25 + 4 = 38, bridging at 6 + 25 + 2 = 33 and the roadshow at 15 + 10 + 6 = 31."},
{
 "key": "td16", "domain": "travel",
 "state": {"decision": "choose a hotel for a five-night audit visit",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"walking distance to the client site": 5, "nightly rate within policy": 4,
                          "quiet rooms": 2, "breakfast included": 1},
           "options": {"Riverside Inn": {"walking distance to the client site": 5, "nightly rate within policy": 2, "quiet rooms": 3, "breakfast included": 5},
                       "Parkgate Hotel": {"walking distance to the client site": 3, "nightly rate within policy": 5, "quiet rooms": 4, "breakfast included": 5},
                       "Station Lodge": {"walking distance to the client site": 4, "nightly rate within policy": 4, "quiet rooms": 2, "breakfast included": 1},
                       "Old Mill House": {"walking distance to the client site": 2, "nightly rate within policy": 5, "quiet rooms": 5, "breakfast included": 3}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "hotel", "type": "choice",
           "question": "Which hotel best satisfies the stated priorities?",
           "options": [{"value": "Riverside Inn"}, {"value": "Parkgate Hotel"},
                       {"value": "Station Lodge"}, {"value": "Old Mill House"}]},
 "target": "Parkgate Hotel", "abstention_cause": None,
 "rationale": "Parkgate totals 15 + 20 + 8 + 5 = 48, ahead of Riverside at 25 + 8 + 6 + 5 = 44, Station Lodge at 20 + 16 + 4 + 1 = 41 and Old Mill at 10 + 20 + 10 + 3 = 43."},
{
 "key": "td17", "domain": "finance_ops",
 "state": "The controller must choose one close-process change. The priorities and weights are: shortening the "
          "close by at least two days (weight 5), audit traceability (weight 4), and disruption to the team during "
          "the change (weight 3, where 5 means least disruption). Rated 1 to 5: automating bank reconciliation "
          "scores 4, 5 and 3; moving to a new ledger scores 5, 5 and 1; standardising journal templates scores 2, 4 "
          "and 5; and hiring a temporary accountant scores 3, 2 and 4. The highest weighted total wins.",
 "field": {"id": "change", "type": "choice",
           "question": "Which close-process change best satisfies the stated priorities?",
           "options": [{"value": "automating bank reconciliation"}, {"value": "moving to a new ledger"},
                       {"value": "standardising journal templates"},
                       {"value": "hiring a temporary accountant"}]},
 "target": "automating bank reconciliation", "abstention_cause": None,
 "rationale": "Automation totals 20 + 20 + 9 = 49, ahead of the new ledger at 25 + 20 + 3 = 48, templates at 10 + 16 + 15 = 41 and the temporary hire at 15 + 8 + 12 = 35."},
{
 "key": "td18", "domain": "logistics",
 "state": {"decision": "choose a site for the new regional cross-dock",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"drive time to the motorway": 4, "rent per square metre": 3,
                          "labour availability": 5, "room to expand": 2},
           "options": {"Site Alder": {"drive time to the motorway": 5, "rent per square metre": 2, "labour availability": 3, "room to expand": 2},
                       "Site Birch": {"drive time to the motorway": 3, "rent per square metre": 3, "labour availability": 5, "room to expand": 3},
                       "Site Cedar": {"drive time to the motorway": 4, "rent per square metre": 3, "labour availability": 4, "room to expand": 5},
                       "Site Dale": {"drive time to the motorway": 2, "rent per square metre": 5, "labour availability": 4, "room to expand": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "site", "type": "choice",
           "question": "Which site best satisfies the stated priorities?",
           "options": [{"value": "Site Alder"}, {"value": "Site Birch"},
                       {"value": "Site Cedar"}, {"value": "Site Dale"}]},
 "target": "Site Cedar", "abstention_cause": None,
 "rationale": "Cedar totals 16 + 9 + 20 + 10 = 55, ahead of Birch at 12 + 9 + 25 + 6 = 52, Dale at 53 and Alder at 45."},
{
 "key": "td19", "domain": "software_incidents",
 "state": {"decision": "choose the on-call model for a growing team",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"response time at night": 5, "sustainable for the team": 5,
                          "cost of allowances": 2, "simplicity to run": 2},
           "options": {"one engineer, week-long rotation": {"response time at night": 4, "sustainable for the team": 2, "cost of allowances": 5, "simplicity to run": 5},
                       "primary and secondary pairs": {"response time at night": 5, "sustainable for the team": 4, "cost of allowances": 2, "simplicity to run": 3},
                       "follow-the-sun across two offices": {"response time at night": 5, "sustainable for the team": 5, "cost of allowances": 1, "simplicity to run": 1},
                       "business hours only with best-effort nights": {"response time at night": 1, "sustainable for the team": 5, "cost of allowances": 5, "simplicity to run": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "model", "type": "choice",
           "question": "Which on-call model best satisfies the stated priorities?",
           "options": [{"value": "one engineer, week-long rotation"}, {"value": "primary and secondary pairs"},
                       {"value": "follow-the-sun across two offices"},
                       {"value": "business hours only with best-effort nights"}]},
 "target": "primary and secondary pairs", "abstention_cause": None,
 "rationale": "Primary and secondary pairs total 25 + 20 + 4 + 6 = 55, just ahead of follow-the-sun at 25 + 25 + 2 + 2 = 54, with the other two models at 50 each."},
{
 "key": "td20", "domain": "hr",
 "state": "The reward team must choose one change to the benefits package within a fixed budget. The priorities and "
          "weights are: value to staff as measured by the last survey (weight 5), retention effect (weight 4), and "
          "administrative overhead (weight 2, where 5 means least overhead). Rated 1 to 5: extra annual leave "
          "scores 5, 4 and 4; a private medical scheme scores 4, 4 and 1; an enhanced pension match scores 3, 5 and "
          "3; and a learning budget scores 4, 3 and 4. The highest weighted total wins.",
 "field": {"id": "benefit", "type": "choice",
           "question": "Which benefit change best satisfies the stated priorities?",
           "options": [{"value": "extra annual leave"}, {"value": "a private medical scheme"},
                       {"value": "an enhanced pension match"}, {"value": "a learning budget"}]},
 "target": "extra annual leave", "abstention_cause": None,
 "rationale": "Extra leave totals 25 + 16 + 8 = 49, ahead of the pension match at 15 + 20 + 6 = 41, medical at 20 + 16 + 2 = 38 and the learning budget at 20 + 12 + 8 = 40."},
{
 "key": "td21", "domain": "retail",
 "state": {"decision": "choose how to handle a batch of slightly damaged stock",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"cash recovered": 4, "brand perception": 5, "warehouse space freed": 3,
                          "staff effort": 1},
           "options": {"discount in store as seconds": {"cash recovered": 4, "brand perception": 2, "warehouse space freed": 4, "staff effort": 3},
                       "sell to a clearance wholesaler": {"cash recovered": 3, "brand perception": 4, "warehouse space freed": 5, "staff effort": 5},
                       "donate to a charity partner": {"cash recovered": 1, "brand perception": 5, "warehouse space freed": 5, "staff effort": 4},
                       "repair and sell at full price": {"cash recovered": 5, "brand perception": 4, "warehouse space freed": 2, "staff effort": 1}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "disposal", "type": "choice",
           "question": "Which option best satisfies the stated priorities?",
           "options": [{"value": "discount in store as seconds"}, {"value": "sell to a clearance wholesaler"},
                       {"value": "donate to a charity partner"}, {"value": "repair and sell at full price"}]},
 "target": "sell to a clearance wholesaler", "abstention_cause": None,
 "rationale": "The wholesaler totals 12 + 20 + 15 + 5 = 52, ahead of repair at 20 + 20 + 6 + 1 = 47, donation at 4 + 25 + 15 + 4 = 48 and seconds at 16 + 10 + 12 + 3 = 41."},
{
 "key": "td22", "domain": "education",
 "state": {"decision": "choose an assessment design for a large first-year module",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"resistance to academic misconduct": 5, "marking workload": 3,
                          "feedback usefulness to students": 4, "accessibility adjustments": 3},
           "options": {"closed-book examination": {"resistance to academic misconduct": 5, "marking workload": 3, "feedback usefulness to students": 1, "accessibility adjustments": 2},
                       "portfolio with supervised checkpoints": {"resistance to academic misconduct": 4, "marking workload": 2, "feedback usefulness to students": 5, "accessibility adjustments": 4},
                       "weekly online quizzes": {"resistance to academic misconduct": 2, "marking workload": 5, "feedback usefulness to students": 3, "accessibility adjustments": 5},
                       "group presentation": {"resistance to academic misconduct": 3, "marking workload": 4, "feedback usefulness to students": 4, "accessibility adjustments": 2}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "assessment", "type": "choice",
           "question": "Which assessment design best satisfies the stated priorities?",
           "options": [{"value": "closed-book examination"},
                       {"value": "portfolio with supervised checkpoints"},
                       {"value": "weekly online quizzes"}, {"value": "group presentation"}]},
 "target": "portfolio with supervised checkpoints", "abstention_cause": None,
 "rationale": "The portfolio totals 20 + 6 + 20 + 12 = 58, ahead of the examination at 25 + 9 + 4 + 6 = 44, quizzes at 10 + 15 + 12 + 15 = 52 and the presentation at 15 + 12 + 16 + 6 = 49."},
{
 "key": "td23", "domain": "travel",
 "state": "A conference organiser must choose one venue. The priorities and weights are: capacity for 400 delegates "
          "(weight 5), transport links (weight 4), catering quality (weight 2) and hire cost (weight 3). Rated 1 to "
          "5 where 5 is best: the Civic Hall scores 5, 5, 2 and 3; the Riverside Centre scores 4, 3, 5 and 4; the "
          "University Atrium scores 3, 4, 3 and 5; and the Harbour Pavilion scores 5, 2, 4 and 2. The highest "
          "weighted total wins and nothing else is in scope.",
 "field": {"id": "venue", "type": "choice",
           "question": "Which venue best satisfies the stated priorities?",
           "options": [{"value": "the Civic Hall"}, {"value": "the Riverside Centre"},
                       {"value": "the University Atrium"}, {"value": "the Harbour Pavilion"}]},
 "target": "the Civic Hall", "abstention_cause": None,
 "rationale": "The Civic Hall totals 25 + 20 + 4 + 9 = 58, ahead of Riverside at 20 + 12 + 10 + 12 = 54, the Atrium at 15 + 16 + 6 + 15 = 52 and the Pavilion at 25 + 8 + 8 + 6 = 47."},
{
 "key": "td24", "domain": "finance_ops",
 "state": {"decision": "choose a collections approach for a slow-paying key account",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"cash collected this quarter": 4, "preserving the commercial relationship": 5,
                          "internal effort": 2, "precedent set for other accounts": 3},
           "options": {"suspend supply until paid": {"cash collected this quarter": 5, "preserving the commercial relationship": 1, "internal effort": 5, "precedent set for other accounts": 4},
                       "agree a phased payment plan": {"cash collected this quarter": 3, "preserving the commercial relationship": 5, "internal effort": 3, "precedent set for other accounts": 2},
                       "escalate to the account director": {"cash collected this quarter": 4, "preserving the commercial relationship": 4, "internal effort": 4, "precedent set for other accounts": 4},
                       "refer to a collections agency": {"cash collected this quarter": 4, "preserving the commercial relationship": 1, "internal effort": 5, "precedent set for other accounts": 3}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "approach", "type": "choice",
           "question": "Which collections approach best satisfies the stated priorities?",
           "options": [{"value": "suspend supply until paid"}, {"value": "agree a phased payment plan"},
                       {"value": "escalate to the account director"},
                       {"value": "refer to a collections agency"}]},
 "target": "escalate to the account director", "abstention_cause": None,
 "rationale": "Escalation totals 16 + 20 + 8 + 12 = 56, ahead of the payment plan at 12 + 25 + 6 + 6 = 49, suspension at 20 + 5 + 10 + 12 = 47 and the agency at 16 + 5 + 10 + 9 = 40."},
{
 "key": "td25", "domain": "logistics",
 "state": {"decision": "choose packaging for a fragile export line",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"damage rate in transit": 5, "material cost": 3, "recyclability": 4,
                          "packing time": 2},
           "options": {"moulded pulp inserts": {"damage rate in transit": 4, "material cost": 3, "recyclability": 5, "packing time": 4},
                       "expanded foam inserts": {"damage rate in transit": 5, "material cost": 4, "recyclability": 1, "packing time": 5},
                       "air pillows": {"damage rate in transit": 3, "material cost": 5, "recyclability": 3, "packing time": 5},
                       "double-wall cartons only": {"damage rate in transit": 2, "material cost": 5, "recyclability": 5, "packing time": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "packaging", "type": "choice",
           "question": "Which packaging best satisfies the stated priorities?",
           "options": [{"value": "moulded pulp inserts"}, {"value": "expanded foam inserts"},
                       {"value": "air pillows"}, {"value": "double-wall cartons only"}]},
 "target": "moulded pulp inserts", "abstention_cause": None,
 "rationale": "Pulp inserts total 20 + 9 + 20 + 8 = 57, ahead of foam at 25 + 12 + 4 + 10 = 51, air pillows at 15 + 15 + 12 + 10 = 52 and cartons at 10 + 15 + 20 + 10 = 55."},
{
 "key": "td26", "domain": "healthcare_admin",
 "state": "The practice must choose one way to cut the wait for routine appointments. The priorities and weights "
          "are: reduction in the wait (weight 5), continuity of care with a named clinician (weight 4), cost "
          "(weight 3, where 5 is cheapest) and ease of explaining the change to patients (weight 1). Rated 1 to 5: "
          "adding evening clinics scores 4, 4, 2 and 4; a triage-first telephone model scores 5, 2, 4 and 2; "
          "recruiting a salaried GP scores 5, 5, 1 and 5; and extending appointment intervals scores 2, 5, 5 and 3. "
          "The highest weighted total wins.",
 "field": {"id": "change", "type": "choice",
           "question": "Which change best satisfies the stated priorities?",
           "options": [{"value": "adding evening clinics"}, {"value": "a triage-first telephone model"},
                       {"value": "recruiting a salaried GP"},
                       {"value": "extending appointment intervals"}]},
 "target": "recruiting a salaried GP", "abstention_cause": None,
 "rationale": "The salaried GP totals 25 + 20 + 3 + 5 = 53, ahead of evening clinics at 20 + 16 + 6 + 4 = 46, triage-first at 25 + 8 + 12 + 2 = 47 and longer intervals at 10 + 20 + 15 + 3 = 48."},
{
 "key": "td27", "domain": "retail",
 "state": {"decision": "choose a delivery promise for the online store",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"conversion rate": 4, "promise reliability": 5, "fulfilment cost": 3},
           "options": {"next day, everything": {"conversion rate": 5, "promise reliability": 2, "fulfilment cost": 1},
                       "two to three days, everything": {"conversion rate": 3, "promise reliability": 5, "fulfilment cost": 4},
                       "next day on stocked lines, five days on the rest": {"conversion rate": 4, "promise reliability": 4, "fulfilment cost": 3},
                       "named-day choice at checkout": {"conversion rate": 4, "promise reliability": 5, "fulfilment cost": 2}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "promise", "type": "choice",
           "question": "Which delivery promise best satisfies the stated priorities?",
           "options": [{"value": "next day, everything"}, {"value": "two to three days, everything"},
                       {"value": "next day on stocked lines, five days on the rest"},
                       {"value": "named-day choice at checkout"}]},
 "target": "two to three days, everything", "abstention_cause": None,
 "rationale": "Two to three days totals 12 + 25 + 12 = 49, ahead of the named-day option at 16 + 25 + 6 = 47, stocked-line splitting at 45 and next-day-everything at 33."},
{
 "key": "td28", "domain": "education",
 "state": {"decision": "choose a laptop scheme for a secondary school",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"reliability over three years": 5, "cost per device": 4,
                          "ease of central management": 3, "weight for students to carry": 2},
           "options": {"Model Ash": {"reliability over three years": 5, "cost per device": 2, "ease of central management": 4, "weight for students to carry": 3},
                       "Model Beech": {"reliability over three years": 3, "cost per device": 5, "ease of central management": 3, "weight for students to carry": 4},
                       "Model Cherry": {"reliability over three years": 4, "cost per device": 4, "ease of central management": 5, "weight for students to carry": 2},
                       "Model Dogwood": {"reliability over three years": 4, "cost per device": 3, "ease of central management": 2, "weight for students to carry": 5}},
           "rule": "Take the highest weighted total."},
 "field": {"id": "model", "type": "choice",
           "question": "Which laptop model best satisfies the stated priorities?",
           "options": [{"value": "Model Ash"}, {"value": "Model Beech"},
                       {"value": "Model Cherry"}, {"value": "Model Dogwood"}]},
 "target": "Model Cherry", "abstention_cause": None,
 "rationale": "Cherry totals 20 + 16 + 15 + 4 = 55, ahead of Ash at 25 + 8 + 12 + 6 = 51, Beech at 15 + 20 + 9 + 8 = 52 and Dogwood at 20 + 12 + 6 + 10 = 48."},
{
 "key": "td29", "domain": "software_incidents",
 "state": {"decision": "how far to prioritise a proposed reliability project",
           "scale": "1 (poor) to 5 (excellent)",
           "priorities": {"incident reduction": 5, "delivery certainty": 3, "cost": 2},
           "options": {"the proposal": {"incident reduction": 4, "delivery certainty": 2, "cost": 2}},
           "priority_bands": ["1: weighted total 0 to 20, do not schedule",
                              "2: weighted total 21 to 30, schedule when capacity allows",
                              "3: weighted total 31 to 40, schedule this quarter",
                              "4: weighted total 41 or more, start immediately"],
           "rule": "Score the proposal on the weighted priorities and read the band."},
 "field": {"id": "priority_band", "type": "ordinal",
           "question": "Which priority band does this proposal fall into?",
           "levels": [{"value": 1, "description": "Do not schedule."},
                      {"value": 2, "description": "Schedule when capacity allows."},
                      {"value": 3, "description": "Schedule this quarter."},
                      {"value": 4, "description": "Start immediately."}]},
 "target": 2, "abstention_cause": None,
 "rationale": "The weighted total is 20 + 6 + 4 = 30, which falls in the 21-to-30 band, one point below the band that would schedule it this quarter."},
{
 "key": "td30", "domain": "finance_ops",
 "state": "A capital request is scored against the company's stated priorities before it goes to committee. The "
          "priorities and weights are: payback inside three years (weight 5), regulatory necessity (weight 4) and "
          "effect on operating cost (weight 3). This request scores 2 on payback, 5 on regulatory necessity and 4 "
          "on operating cost, each on a 1 to 5 scale where 5 is best. The committee reads the weighted total "
          "against four bands: 0 to 25 is band 1 and is declined, 26 to 35 is band 2 and is deferred, 36 to 45 is "
          "band 3 and is approved subject to conditions, and 46 or more is band 4 and is approved outright.",
 "field": {"id": "committee_band", "type": "ordinal",
           "question": "Which committee band does this capital request fall into?",
           "levels": [{"value": 1, "description": "Band 1, declined."},
                      {"value": 2, "description": "Band 2, deferred."},
                      {"value": 3, "description": "Band 3, approved subject to conditions."},
                      {"value": 4, "description": "Band 4, approved outright."}]},
 "target": 3, "abstention_cause": None,
 "rationale": "The weighted total is 10 + 20 + 12 = 42, which sits in the 36-to-45 band."},
]
